### ISSUE TITLE
Missing stable branch in cortx-build:centos-7.8.2003

### ISSUE THREAD

**Issue by christina-00** [Seagate/cortx#1036]
Execute Step 4 in [Release Build Creation](https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst) throws the following error.
[root@ssc-vm-4297 cortx]# docker run --rm -v /var/artifacts:/var/artifacts -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-build:centos-7.8.2003 make checkout BRANCH=stable
*************** checkout code *********************
pushd cortx-workspace && \
        for component in $(ls -1d cortx-* | grep -Evx 'cortx-experiments||cortx-posix'); do pushd $component; git pull -p --all; git checkout $BRANCH || exit 1; popd ; done  && \
popd || (echo "ERROR: Failed to checkout specified branch/tag Exiting..."; exit 1)
/cortx-workspace /
/cortx-workspace/cortx-ha /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
/cortx-workspace /
/cortx-workspace/cortx-hare /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
/cortx-workspace /
/cortx-workspace/cortx-management-portal /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
/cortx-workspace /
/cortx-workspace/cortx-manager /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
/cortx-workspace /
/cortx-workspace/cortx-monitor /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
/cortx-workspace /
/cortx-workspace/cortx-motr /cortx-workspace /
Fetching origin
Already up-to-date.
Already on 'stable'
Your branch is up-to-date with 'origin/stable'.
/cortx-workspace /
/cortx-workspace/cortx-multisite /cortx-workspace /
Fetching origin
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

error: pathspec 'stable' did not match any file(s) known to git.
make: *** [checkout] Error 1
[root@ssc-vm-4297 cortx]#

**Comment by shailesh-vaidya** [comment]
@christina-00  This is caused due to newly added submodule `cortx-multisite` . Let me get this fixed.

**Comment by justinzw** [comment]
Thanks @shailesh-vaidya is there a workaround here? What is the fix so @christina-00 can go about building this?

**Comment by shailesh-vaidya** [comment]
@christina-00 - You can use below command to check-out `stable` branch code for all components as of now,
```
cd /root/cortx
BRANCH=stable
for component in $(ls -1d cortx-* | grep -Evx 'cortx-experiments||cortx-posix||cortx-multisite'); do pushd $component; git pull -p --all; git checkout $BRANCH || exit 1; popd ; done
```
