### ISSUE TITLE
Unable to send test email in CORTX notifications setting

### ISSUE THREAD

**Issue by christina-00** [Seagate/cortx#1038]
When configuring the Notification settings at [CORTX Onboarding](https://ssc-vm-4297.colo.seagate.com:28100/#/onboarding) page with the following information, hit "Authentication failed" error. What is the correct configuration? 

![image](https://user-images.githubusercontent.com/67787582/117958290-74e5c100-b34d-11eb-9278-a7412da7f945.png)

**Comment by justinzw** [comment]
@christina-00 I just wanted to check is this indeed an available smtp server?

Do you really have the domain "testmail.com"?

**Comment by christina-00** [comment]
> @christina-00 I just wanted to check is this indeed an available smtp server?
> 
> Do you really have the domain "testmail.com"?

I don't think "testmail.com" is a valid domain. The above configurations are given by the CORTX Test team. I tried with "seagate.com" and it doesn't work as well.

**Comment by justinzw** [comment]
Thanks @christina-00  I think it needs to be a valid smtp server. Can you email me the instructions from the CORTX test team?
I'll try them out.

justin.woo at seagate dot com

**Comment by shailesh-vaidya** [comment]
@kupranay - We are trying to configure SMTP in single node CORTX deployment and it's not working. I tried configuration from QA team and asked @christina-00 to try it out. However it's not working. Could you please ask someone help into this.

**Comment by justinzw** [comment]
With the right configurations. @christina-00 managed to configure the notifications.
