### ISSUE TITLE
BE Components picture needs higher resolution

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#104]
BE components image is not clear, hard to read, see here : 

https://github.com/Seagate/cortx/blob/master/doc/be/BE_TheMetadataBackend.md#be-components-relationship

https://github.com/Seagate/cortx/blob/master/doc/be/images/be-components.png

**Comment by mukul-seagate11** [comment]
@all, can this issue be closed if addressed?

**Comment by mukul-seagate11** [comment]
@johnbent @max-seagate, any update on this issue or the same can be closed?

**Comment by hessio** [comment]
@max-seagate can you take a look at this issue when you get a chance?

**Comment by r-wambui** [comment]
@max-seagate Any update on this, has this been completed? if yes, can we close the issue?

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~744292] [~532357] [~747271] [~930816] [~935494] 
I would assume we have since updated out 'backend images' in recent months?  is this addressed already?

**Comment by cortx-admin** [comment]
> Ujjwal Lanjewar commented in Jira Server:

There has been significant changes to the Architecture, in the last 5-6 months. I think the image may need to be re looked at and updated. Can be assigned to someone for completion.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~535110] I believe we have some documentation folks on the Opensource team.  Would they update these diagrams (maybe with the help of [~530903] [~520479] to identify the recent collateral)?

**Comment by chandradharraval** [comment]
@max-seagate , @nikitadanilov - Do we have updated diagram for this?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

[~522123] - Can we confirm latest design for BE and generate new image?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
