### ISSUE TITLE
Location of CORTX Technical Overview & brainshark video

### ISSUE THREAD

**Issue by christina-00** [Seagate/cortx#1068]
https://github.com/Seagate/cortx/blob/main/doc/architecture.md
1. Should the **CORTX Technical Overview** belongs under **Seagate** folder? Currently, it is pointing to **Saumya Sauder**? 
2. The brainshark link is not accessible outside of Seagate network. Should we make it accessible? 

![image](https://user-images.githubusercontent.com/67787582/119973926-a5348d00-bfe6-11eb-9bb1-a6e76aacca48.png)

**Comment by hessio** [comment]
Thanks @christina-00 yes I think you are right I don't think this should point to @Saumya-Sunder branch, and also you are correct this BrainShark video is not available to the open-source community and I think we should remove it.

**Comment by justinzw** [comment]
@johnbent @novium258  Should we put the brainshark video up on youtube? or is it already out of date.

**Comment by johnbent** [comment]
@justinzw , we should definitely add it to youtube.  @TechWriter-Mayur , can you please do the needful?

**Comment by mukul-seagate11** [comment]
https://github.com/Seagate/cortx/pull/1071 raised for the issue reported, Patrick close once done

**Comment by TechWriter-Mayur** [comment]
@novium258 Can we add Seagate Brainshark course video to YouTube?

**Comment by novium258** [comment]
@TechWriter-Mayur Yes, definitely put in the ticket to get it up!
