### ISSUE TITLE
Error adding new S3 account in CORTX GUI

### ISSUE THREAD

**Issue by christina-00** [Seagate/cortx#1069]
I am using a Seagate cloud VM. Hit the following error when trying out the guide at https://github.com/Seagate/cortx/blob/main/doc/testing_io.rst

![image](https://user-images.githubusercontent.com/67787582/119977030-7fa98280-bfea-11eb-8dad-1a06b79b0911.png)

**Comment by mukul-seagate11** [comment]
@christina-00, Check whether below service is running,

systemctl status s3authserver

and If in failed/stopped state then start the service,

systemctl status s3authserver

Also, check whether port, 9080 is open & listening

**Comment by christina-00** [comment]
It seems to be down. What is the command to start the service? 

> **[root@ssc-vm-4297 ~]# systemctl status s3authserver**
> ● s3authserver.service - Motr-S3 Auth Server
>    Loaded: loaded (/usr/lib/systemd/system/s3authserver.service; enabled; vendor preset: disabled)
>    Active: inactive (dead) since Fri 2021-05-21 07:10:45 MDT; 1 weeks 0 days ago
>  Main PID: 60873 (code=killed, signal=TERM)
> 
> Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

I tried to start the cortx cluster but it seems there are other components (ioservice, confd, s3server) which are not running even after I started it.

> **[root@ssc-vm-4297 ~]# cortx cluster start**
> {"status": "InProgress", "msg": "Cluster start operation performed"}
> **[root@ssc-vm-4297 ~]# hctl status**
> Data pool:
>     # fid name
>     0x6f00000000000001:0x23 'storage-set-1__sns'
> Profile:
>     # fid name: pool(s)
>     0x7000000000000001:0x3a 'Profile_the_pool': 'storage-set-1__sns' None None
> Services:
>     ssc-vm-4297.colo.seagate.com  (RC)
>     [started]  hax        0x7200000000000001:0x6   192.168.57.193@tcp:12345:1:1
>     [offline]  ioservice  0x7200000000000001:0x9   192.168.57.193@tcp:12345:2:1
>     [offline]  confd      0x7200000000000001:0x14  192.168.57.193@tcp:12345:2:2
>     [offline]  s3server   0x7200000000000001:0x17  192.168.57.193@tcp:12345:3:1
>     [unknown]  m0_client  0x7200000000000001:0x1a  192.168.57.193@tcp:12345:4:1
>     [unknown]  m0_client  0x7200000000000001:0x1d  192.168.57.193@tcp:12345:4:2
>     [unknown]  m0_client  0x7200000000000001:0x20  192.168.57.193@tcp:12345:4:3
>

**Comment by TechWriter-Mayur** [comment]
@christina-00 : try to run to start S3authserver:

`systemctl start s3authserver`

**Comment by justinzw** [comment]
@christina-00 it seems odd that multiple systems seem down. Maybe you can give us access to the machine and we can ssh into it to debug. Feel free to share with me the connection details over e-mail.

**Comment by christina-00** [comment]
@justinzw @TechWriter-Mayur @mukul-seagate11 It's working right now. My VM is affected by an outage according to the lab admin. I think that's probably the reason why I was unable to start the CORTX cluster. All components except the m0_client are started now. The s3authserver is also up and running now. I am able to add the S3 account.

> **[root@ssc-vm-4297 ~]# hctl status**
> Data pool:
>     # fid name
>     0x6f00000000000001:0x23 'storage-set-1__sns'
> Profile:
>     # fid name: pool(s)
>     0x7000000000000001:0x3a 'Profile_the_pool': 'storage-set-1__sns' None None
> Services:
>     ssc-vm-4297.colo.seagate.com  (RC)
>     [started]  hax        0x7200000000000001:0x6   192.168.57.193@tcp:12345:1:1
>     [started]  ioservice  0x7200000000000001:0x9   192.168.57.193@tcp:12345:2:1
>     [started]  confd      0x7200000000000001:0x14  192.168.57.193@tcp:12345:2:2
>     [started]  s3server   0x7200000000000001:0x17  192.168.57.193@tcp:12345:3:1
>     [unknown]  m0_client  0x7200000000000001:0x1a  192.168.57.193@tcp:12345:4:1
>     [unknown]  m0_client  0x7200000000000001:0x1d  192.168.57.193@tcp:12345:4:2
>     [unknown]  m0_client  0x7200000000000001:0x20  192.168.57.193@tcp:12345:4:3
>  **[root@ssc-vm-4297 ~]# systemctl status s3authserver**
> ● s3authserver.service - Cluster Controlled s3authserver
>    Loaded: loaded (/usr/lib/systemd/system/s3authserver.service; enabled; vendor preset: disabled)
>   Drop-In: /run/systemd/system/s3authserver.service.d
>            └─50-pacemaker.conf
>    Active: active (running) since Fri 2021-05-28 10:14:00 MDT; 18h ago
>  Main PID: 14853 (startauth.sh)
>    CGroup: /system.slice/s3authserver.service
>            ├─14853 /bin/sh -x /opt/seagate/cortx/auth/startauth.sh
>            └─14856 java -jar AuthServer-1.0-0.jar
>

**Comment by christina-00** [comment]
However, I do see a warning like below after the S3 account is created successfully. I wasn't able to connect using Cyberduck after that. Can anyone shed some light on this? 
![image](https://user-images.githubusercontent.com/67787582/120067980-f1e49a80-c0b0-11eb-8ff2-f777a521e47d.png)
![image](https://user-images.githubusercontent.com/67787582/120068030-307a5500-c0b1-11eb-9ab1-fffe9b059d48.png)
![image](https://user-images.githubusercontent.com/67787582/120068036-34a67280-c0b1-11eb-8801-dd8c8fd6c8b4.png)

**Comment by mukul-seagate11** [comment]
@christina-00, I see you are testing on SSC VM as we have to troubleshoot as well as debug the network & firewall settings from infra perspective as in your error message SSC VM connection is getting refused so I would suggest, you to use the hypervisor's install locally i.e. VMware Workstation as the community will be tested with same use case

**Comment by christina-00** [comment]
@mukul-seagate11 I do see few obstacles when using SSC VM. Some of the guideline (for eg, changing hostname, setting up email notification) would not work due to limitations with SSC VM. I am thinking we should discourage Seagators from using SSC VM going forward if this is causing too much issues. What do you think?

**Comment by hessio** [comment]
I strongly agree with you @christina-00 but I think the issue with this right now is the security. I think it would be great if we could all use the same systems or at least very similar. I will try to bring this issue up with others @christina-00 thanks for your input. [😊](https://emojipedia.org/smiling-face-with-smiling-eyes/)

**Comment by AshwiniS-Borse** [comment]
Not sure what QA is expected to do here. Assigning to @DeepakChoudahry, please assign it

**Comment by mukul-seagate11** [comment]
@sachitanands, please address as per reported

**Comment by nileshgovande** [comment]
1)What type of deployment it is ? R1 (cortx-1.0) or R2 (main) ? 
2)OVA or provisioning setup ? 

It looks like Cyberduck seems to contact management IP. Is it supposed to work that way ?

**Comment by mukul-seagate11** [comment]
@christina-00, many fixes has gone in OVA R1 & R2 and now new version of OVA R1 is published so try a fresh build on hypervisor
