### ISSUE TITLE
Bootstrap script in Virtual Appliance v1.0.3 not working out of the box

### ISSUE THREAD

**Issue by yoketong-t** [Seagate/cortx#1078]
Following the guide @ [CORTX on Open Virtual Appliance](https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst), I was able to import the OVA into VMware Workstation 14 Pro. I have made sure that the network configuration are correct (DHCP + bridging to the correct NIC).

However, as I attempt to run the bootstrap.sh script (/opt/seagate/cortx/provisioner/cli/virtual_appliance/bootstrap.sh), I was faced with errors returning from the script.

Errors from the script:
![image](https://user-images.githubusercontent.com/73337642/120731219-bbc27300-c515-11eb-80db-36932730ec0b.png)

Here are my network interfaces returned from _"ip a l"_:
![image](https://user-images.githubusercontent.com/73337642/120731412-2a073580-c516-11eb-9a2d-b73f8282c54f.png)

I see that the bootstrap script is suppose to detect the network configurations and update/modify the "_/etc/haproxy/haproxy.cfg_" and "_/etc/hosts_" files accordingly. But there were problems with "ens34" and "ens34" isn't one of my interfaces.

I referred to some of the discussions related to this problem and found related discussions in the following:
[Virtual Images error installing, port 8500 connection refused. #379](https://github.com/Seagate/cortx/discussions/379)
[Virtual Images error installing, port 8500 connection refused. #845](https://github.com/Seagate/cortx-prvsnr/issues/845)

There was a [comment](https://github.com/Seagate/cortx/discussions/379#discussioncomment-89663) that mentioned:
> Manually modifying both files to remove the 192.168.X.X references, replacing with the IP for the ens256 interface finally resulted in success for the s3-sanity-test.

From there, I made the some changes to my network configuration, including:
- re-naming my network interfaces so that they are named in "sequence"
- set the IP addresses to static but in sequence (may not be necessary, but I did it anyway)

_"ip a l"_ after the changes:
![image](https://user-images.githubusercontent.com/73337642/120732585-283e7180-c518-11eb-8ce4-f53f66e66878.png)

Thereafter, the bootstrap script executed without any errors.

I suppose the OVA and bootstrap script should be a quick way for someone not familiar with CORTX to quickly set-up a test system so that he/she can play around and start understanding the system. The current situation seems to require the user to configure more then just setting the DHCP and bridging. Suggesting to either fix the bootstrap script or have more documentation on the OVA set-up guide.

**Comment by justinzw** [comment]
Hi @yoketong-t  thank you for reporting this issue and fixing it on your system. This is indeed odd and not something we have reproduced on our systems using the same setup. I'll reach out and schedule a meeting with you to look at this together.

**Comment by mukul-seagate11** [comment]
@justinzw, does this issue has been addressed as the its from 1.0.3 release?

**Comment by mukul-seagate11** [comment]
Please close the issue If the same has been addressed

**Comment by mukul-seagate11** [comment]
Haven't received any update so please feel free to reopen the issue if any issue is observed
