### ISSUE TITLE
Link to deploy CORTX OVA is not pointing to a valid path

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx#1087]
The link to Run a pre-built CORTX OVA on a single node is not working. Apparently, the page is now moved to another dir.
Original path = https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst
New path      = https://github.com/Seagate/cortx/blob/main/doc/OVA/1.0.4/CORTX_on_Open_Virtual_Appliance.rst 

This page contains the invalid link: https://github.com/Seagate/cortx/blob/main/QUICK_START.md 
I can create a PR to solve this and scan other pages that might embed this invalid link.  Please let me know, thanks!

**Comment by johnbent** [comment]
Thanks Dan!  Yes, please go ahead and scan and find all broken links!

**Comment by daniarherikurniawan** [comment]
Thanks, I will work on this tomorrow.
