### ISSUE TITLE
CORTX QUICK START GUIDE item 9 link is not valid 

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#109]
Submitting contributions link to demo video 

404 NOT FOUND

**Comment by Saumya-Sunder** [comment]
Hey @justinzw, gentle reminder, you need to add the videos on vimeo to the quickstart guide.

**Comment by Saumya-Sunder** [comment]
This is automatically resolved here https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md as @johnbent edited the Contributing guide and merged it with Quickstart.md
