### ISSUE TITLE
Combine coding guidelines

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1094]
@Saumya-Sunder , can you please copy everything from this [confluence page](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/219612844/Coding+Guidelines) into our [github page](https://github.com/Seagate/cortx/blob/main/doc/CodeStyle.md)?  But please eliminate any redundancy.  If there are any contradictions, please ask myself or @ujjwalpl for guidance.  Then delete everything in the confluence page and replace it with:

This page has been moved to [github](https://github.com/Seagate/cortx/blob/main/doc/CodeStyle.md).

Thanks!

**Comment by Saumya-Sunder** [comment]
Hey @johnbent, sure.

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, Is anything pending on this issue otherwise please update & close accordingly

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, If this issue has been addressed then we can close the same?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can this issue be closed?

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Closed

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
