### ISSUE TITLE
Documentation naming convention. 

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx#1107]
We should define and follow the standard naming conventions for naming documents. Currently few are all small, all capital and mix.
```
assets/
be/
cla/
images/
integrations/
meetings/
PDFs/
RELEASENOTES/
scaleout/
```

**Comment by TechWriter-Mayur** [comment]
Created the PR #1108 to address this issue.

**Comment by mukul-seagate11** [comment]
Issue addressed, hence closing
