### ISSUE TITLE
Tested by Section needed

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1109]
[https://github.com/Seagate/cortx/blob/main/doc/Community-Build/Building-CORTX-From-Source-for-SingleNode.md](https://github.com/Seagate/cortx/blob/main/doc/Community-Build/Building-CORTX-From-Source-for-SingleNode.md)

Needs a tested-by section.  @TechWriter-Mayur , can you please do the needful?

**Comment by TechWriter-Mayur** [comment]
Sure @johnbent, let me add the tested by section.

**Comment by mukul-seagate11** [comment]
Issue has been addressed, hence closing
