### ISSUE TITLE
PDF needs to be rotated

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1111]
[https://github.com/Seagate/cortx/blob/main/doc/meetings/PDFs/MTA_april.pdf](https://github.com/Seagate/cortx/blob/main/doc/meetings/PDFs/MTA_april.pdf)

@TechWriter-Mayur , can you please download and fix this PDF?  The rotation is not correct.  Thanks.

**Comment by TechWriter-Mayur** [comment]
Raised the #1114 for the same.

**Comment by mukul-seagate11** [comment]
As issue has been addressed in https://github.com/Seagate/cortx/pull/1114 so closing the issue
