### ISSUE TITLE
cortx GUI refused to connect

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx#1131]
Hello, I was following [this OVA QSG](https://github.com/Seagate/cortx/blob/main/doc/ova/1.0.4/CORTX_on_Open_Virtual_Appliance.rst) on ova 1.0.4.
I'm using VMWare Workstation on a Windows10 laptop.
And I'm currently trying to[ configure the Cortx GUI](https://github.com/Seagate/cortx/blob/main/doc/Preboarding_and_Onboarding.rst).

However, when I tried to open https://<management IP>/#/preboarding/welcome on my browser, I got the error that "10.0.0.253 refused to connect." Here 10.0.0.253 is my management IP in the VM.
![1d751c1eec73b2745a48e343e40e32f](https://user-images.githubusercontent.com/23745174/127401736-7d08a494-0d47-412d-a960-9efa7c5f1ed6.png)

I double checked to make sure my management IP is correct.

Actually I can successfully ssh into this management IP from my windows laptop.
However, the http doesn't work.

Any suggestions?

**Comment by mengwanguc** [comment]
This is output of `ip a l`:

```
[cortx@cortx-ova ~]$ ip a l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:96:a5:87 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.253/24 brd 10.0.0.255 scope global ens32
       valid_lft forever preferred_lft forever
    inet6 2601:240:cf02:fb0:20c:29ff:fe96:a587/64 scope global mngtmpaddr dynamic
       valid_lft 294956sec preferred_lft 294956sec
    inet6 fe80::20c:29ff:fe96:a587/64 scope link
       valid_lft forever preferred_lft forever
3: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:96:a5:91 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.11/24 brd 10.0.0.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 2601:240:cf02:fb0:20c:29ff:fe96:a591/64 scope global mngtmpaddr dynamic
       valid_lft 294956sec preferred_lft 294956sec
    inet6 fe80::20c:29ff:fe96:a591/64 scope link
       valid_lft forever preferred_lft forever
4: ens34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:96:a5:9b brd ff:ff:ff:ff:ff:ff
    inet 192.251.254.254/24 brd 192.251.254.255 scope global ens34
       valid_lft forever preferred_lft forever
    inet6 2601:240:cf02:fb0:20c:29ff:fe96:a59b/64 scope global mngtmpaddr dynamic
       valid_lft 294956sec preferred_lft 294956sec
    inet6 fe80::20c:29ff:fe96:a59b/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by mengwanguc** [comment]
This is resolved by doing the following steps:

1. Open port 28100 by running
```
salt '*' cmd.run "firewall-cmd --zone=public-data-zone --add-port=28100/tcp --permanent"
salt '*' cmd.run "firewall-cmd --reload"
```

2. Visit port 28100:
https://<management IP>:28100/#/preboarding/welcome

Actually, these solutions were in the guide in old versions. However they were removed.
Step 1 was removed in #831. In this PR the troubleshooting was removed.
Step 2 was modified in #1096 . In this PR, the guide no longer uses port 1096.

Hi @mukul-seagate11 and @TechWriter-Mayur , may I ask why did we no longer uses port 28100?

**Comment by mukul-seagate11** [comment]
@mengwanguc, As you are OVA 1.0.4 where port 28100 is required in URL so thanks for reported & let me take forward to fix the Wiki page

Also, we dont have to open the port or tamper the configuration as the port, 28100 is already opened

**Comment by mengwanguc** [comment]
Thanks @mukul-seagate11 ! 

So I guess we don't need to specify port 28100 in OVA 2.0.0? (and that's why the port number is removed from the doc?)

I will try out OVA 2.0.0 later.

I was working on OVA 1.0.4 mainly because in Hackathon participants will be encouraged to use OVA 1.0.4 based on[ this slack discussion](https://cortxcommunity.slack.com/archives/G01EZQ2LUH1/p1627495168156800?thread_ts=1627456555.116000&cid=G01EZQ2LUH1)

And thanks for fixing this issue in the PR!

**Comment by mukul-seagate11** [comment]
> So I guess we don't need to specify port 28100 in OVA 2.0.0? (and that's why the port number is removed from the doc?)

yes you are correct
