### ISSUE TITLE
Unable to do `yum install` in the OVA

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx#1133]
Hello I'm running OVA 1.0.4 in VMWare Workstation on a Windows10 laptop.

I tried to do "sudo yum install nano" but got the following error message:

```
[cortx@cortx-ova ~]$ sudo yum install nano
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
http://cortx-storage.colo.seagate.com/releases/opensource_builds/ova_builds/centos-7.8.2003/ova-build-44//cortx_iso/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: cortx-storage.colo.seagate.com; Unknown error"
Trying other mirror.
No package nano available.
Error: Nothing to do
```

Same error happens when doing `yum install` for other packages.

From error message, this is because `yum` always tries to query packages from "cortx-storage.colo.seagate.com", but "cortx-storage.colo.seagate.com" looks like an internal site and cannot be accessed by users not using Seagate machine/network.

Seems not good practice since we want the community could use this OVA.
Guess we need to fix this?

**Comment by johnbent** [comment]
@mengwanguc , which QSG are you following?

**Comment by shailesh-vaidya** [comment]
@mengwanguc  Thanks for raising this issue. We advise not to install any package on OVA system as it might cause an adverse impact on CORTX services. Hence we disable all yum repositories in OVA VM. 

We have fixed the internal URL configured in yum in the latest OVA release available at - https://github.com/Seagate/cortx/releases/tag/cortx-ova-2.0.0-264 

You can build CORTX from source code and run it on a single node If you are installing nano for some debug purpose. Please refer - https://github.com/Seagate/cortx/blob/main/doc/community-build/Building-CORTX-From-Source-for-SingleNode.md 
You should be able to install packages in this environment.

**Comment by mengwanguc** [comment]
Hi @johnbent , I was following https://github.com/Seagate/cortx/blob/main/doc/ova/1.0.4/CORTX_on_Open_Virtual_Appliance.rst

In step 17, it directs me to [Checking Health Doc](https://github.com/Seagate/cortx/blob/main/doc/checking_health.rst)
And in Checking Health Doc, it tells users to use `dstat ` to show IO activity.
However, OVA 1.0.4 doesn't have dstat installed. That's why I raised this issue.

Hi @shailesh-vaidya , thanks, I will try 2.0.0 later.

I was trying 1.0.4 mainly because in the hackathon participants are encouraged to use 1.0.4 based on this slack discussion: https://cortxcommunity.slack.com/archives/G01EZQ2LUH1/p1627456555116000

so I wanted to make sure 1.0.4 works smoothly for me.

**Comment by johnbent** [comment]
Thanks @mengwanguc !  @shailesh-vaidya and @mukul-seagate11 , seems like it is OK to disable yum (but not to show the error due to internal link) but seems like we need to install dstat.  Agreed?

**Comment by shailesh-vaidya** [comment]
@johnbent  Yes, we should do that. 
@mengwanguc  We will add `dstat` command in the next OVA release.  CC: @mukul-seagate11

**Comment by mukul-seagate11** [comment]
OK, as reported & noted, dstat command will be added in next OVA release
