### ISSUE TITLE
Failure while setting up dev environment for cortx-s3server

### ISSUE THREAD

**Issue by mehjoshi** [Seagate/cortx#115]
There is a failure while setting up dev environment for cortx-s3server.

I saw this failure in the script/env/dev/init.sh script that is run while trying to setup a development environment for cortx-s3server.
The failure happens while installing the packages bundled in ansible/awscli-bundle.zip. The install script in the bundle fails suggesting duplicates for some of the packages. I was able to circumvent the problem by deleting the duplicates from the package folder and then running the install script manually. After that, I commented out the relevant portion from the ansible/common_dev_setup.yml and ran the init.sh script again. This time it ran to completion without any failures.
Here, if the diff between my changed copy and the original file common_dev_setup.yml file.

cortx-s3server]# diff ansible/common_dev_setup.yml ansible/common_dev_setup.orig.yml
57a58,67
> - name: Install and configure awscli on RHEL
>   when: ansible_distribution == "RedHat"
>   command: "{{ item }}"
>   with_items:
>   - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
>   - unzip awscli-bundle.zip
>   - ./awscli-bundle/install -b ~/bin/aws
>   - rm -rf awscli*
>   no_log: true
>

**Comment by nileshgovande** [comment]
no response from @mehjoshi for 2 months. Closing

**Comment by shailesh-vaidya** [comment]
@nileshgovande @mukul-seagate11  Can we close this issue.

**Comment by mukul-seagate11** [comment]
> no response from @mehjoshi for 2 months. Closing

@nileshgovande closing the issue as per your comment
