### ISSUE TITLE
Is there an easy way to test I/O performance ？

### ISSUE THREAD

**Issue by 1156564544** [Seagate/cortx#1153]
In addition to using the s3 client, is there a simpler data input and output method for cortx ?

**Comment by 1156564544** [comment]
![image](https://user-images.githubusercontent.com/49397140/127985609-0829dcd7-052c-4bb8-8007-e6bca131c1bf.png)
I can't create an s3 account, so I would like to ask if there are other ways to achieve cortx data input and output ？

**Comment by 1156564544** [comment]
![image](https://user-images.githubusercontent.com/49397140/127986368-f120080d-7cf6-4114-97e8-7e2d14008752.png)
I can not create a s3 account.
Is there any other way to input and output data to cortx ?

**Comment by hessio** [comment]
You can use cortx-motr to read and write data but s3 is the simplest way to do IO in cortx.

Can you check that all the services are running? Also has this cortx installation been left idle for a long time by any chance? I am trying to figure out why this issue might occur. 

Can you check all the services are running correctly:

```
systemctl status s3authserver
systemctl status haproxy
```

If they are not active you can run:

```
systemctl start s3authserver
systemctl start haproxy
```

**Comment by 1156564544** [comment]
@hessio Thank you for your reply. At the beginning, I installed cortx version 1.0.4 according to the steps in the official documentation. After the installation, the haproxy service could not be started. Now I use cortx version 1.0.3 and can create s3 account.

**Comment by hessio** [comment]
Oh ok what hypervisor are you using?

**Comment by mukul-seagate11** [comment]
Any update on this issue?

**Comment by mukul-seagate11** [comment]
@1156564544, Do you have any update on this issue?

**Comment by hessio** [comment]
Hi @1156564544 is there any update on this issue, if not I will close this issue?

**Comment by hessio** [comment]
Hi @1156564544 is there any update on this issue?

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

[~930816], any update on this otherwise can be closed?

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

I have not heard any new update

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed
