### ISSUE TITLE
Kernel modules in the docker images.

### ISSUE THREAD

**Issue by nikitadanilov** [Seagate/cortx#1159]
I am trying to use ghcr.io/seagate/cortx-build:centos-7.8.2003.

$(uname -r) gives "5.10.25-linuxkit", but in /lib/modules there are only 3.10.0-1160.25.1.el7.x86_64 and 3.10.0-1160.el7.x86_64.

As a result, build of motr (and build of any other software relying on kernel modules, I assume), fails.

Is there a workaround?

**Comment by hessio** [comment]
Hi @nikitadanilov I think this is a workaround for your issue: #1130

**Comment by johnbent** [comment]
@hessio and @nikitadanilov , what guide was this following?

**Comment by hessio** [comment]
I am thinking @nikitadanilov was trying to use the community build guide: [https://github.com/Seagate/cortx/tree/main/doc/community-build](https://github.com/Seagate/cortx/tree/main/doc/community-build) and if you go to this guide step 4 you call docker run to use this docker container https://github.com/Seagate/cortx/blob/main/doc/community-build/Generate-Cortx-Build-Stack.md

**Comment by nikitadanilov** [comment]
I am doing a manual build within a docker on macos.
