### ISSUE TITLE
Standardize Git Protocol (https / ssh)

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx#116]
### I think we should standardize git protocols among all submodules
Most if not all submodules protocol uses https (e.g. https://github.com/Seagate/cortx-s3server.git).
However, in the [cortxs3 documentation](https://github.com/Seagate/cortx/blob/master/doc/CortxS3ServerQuickStart.md), it recommends (instruct) to setup ssh access which won't work when you git clone recursively. You still need to setup PAT (as noted in doc) and I think we should decide which protocol to stick with.

I personally prefer ssh but I guess whichever should do just fine as long as users do not need to setup double access.

**Comment by Saumya-Sunder** [comment]
Closing this as we have updated the S3 server documentation.
