### ISSUE TITLE
EOS-26653: Add k8s submodule

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1347]
@priyankdal , can you please assign someone to add a [https://github.com/Seagate/cortx-k8s](https://github.com/Seagate/cortx-k8s) submodule to this parent repo?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26653. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by mukul-seagate11** [comment]
@venkuppu-chn

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

[~744954], can you please help get this assigned?

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

[~747271], can you please help get this scheduled?

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

[~747271], when we do this can we also do the same for the cortx-re module? If not, please let me know and I'll create another ticket.

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

[~535110], We will address it in the same ticket for cortx-re repository as well.

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

[~747271], We have to rename/create a new token in RE repo to follow the uniformity. Other repositories have the secrets as ACCESS_TOKEN but RE has just TOKEN.

!image-2021-12-22-00-03-54-315.png!

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

[~747271], Also please create a secrets as ACCESS_TOKEN in cortx-k8s repository.

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

PRs:

Cortx Repo:

[https://github.com/Seagate/cortx/pull/1370]

 

RE Repo:

[https://github.com/Seagate/cortx-re/pull/765]

 

K8s Repo:

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

Review Required

**Comment by cortx-admin** [comment]
> Venkatesh K commented in Jira Server:

[~747271], Can you please merge the PRs.

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

[~744417] and [~747271], what is status of this please?

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Request has already been addressed by raising below PRs:

https://github.com/Seagate/cortx/pull/1370
https://github.com/Seagate/cortx-re/pull/775
https://github.com/Seagate/cortx-re/pull/774
https://github.com/Seagate/cortx-k8s/pull/41

Hence closing request.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Done

**Comment by cortx-admin** [comment]
> Gaurav Chaudhari commented in Jira Server:

{panel:bgColor=#c1c7d0}h2. hare - main branch build pipeline SUCCESS
h3. Build Info:  
* Author: noreply
* Component Build  :  347 
* Release Build    :  847  

  h3. Artifact Location  :  
*  http://cortx-storage.colo.seagate.com/releases/cortx/github/main/centos-7.9.2009/847 
{panel}
