### ISSUE TITLE
EOS-26654: Parent QSG needs to be updated

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#1348]
@gregnsk  instructions for k8s deployment: 

[https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md](https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md)  
 

We need to add a link to this from our parent QSG. Who is driving this? I'll create a github issue as well. Also, I think now that we have k8s, we need to completely redo our parent QSG. I think it should basically be:

1.  Build source into containers
2.  Run from containers
3.  Run from OVA
4.  Motr QSG

Anything else?

**Comment by johnbent** [comment]
@priyankdal can you please get this assigned and scheduled? I think it already should have happened at the end of PI4. You can work with @novium258 because @swatid-seagate might be able to do this work.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26654. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by johnbent** [comment]
What is the relationship between @gregnsk instructions in k8s repo and this PR in this repo which I worry is adding a redundant set of instructions: #1341.

**Comment by mukul-seagate11** [comment]
@swatid-seagate

**Comment by swatid-seagate** [comment]
@mukul-seagate11 please help me understand which link to update or do we need to add a new point in QSG.md file?

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

As discussed with Shailesh, will work on following for QSG update.
 * Image creation - [https://github.com/Seagate/cortx/blob/main/doc/community-build/docker/cortx-all/README.md]
 * Deployment - [https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md]
 * RPM - [https://github.com/Seagate/cortx/blob/main/doc/community-build/Generate-Cortx-Build-Stack.md]

 * Image - [https://github.com/Seagate/cortx/blob/main/doc/community-build/docker/cortx-all/README.md]

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

QSG is updated and raised a PR for the same. Please review and share your suggestion:

[https://github.com/Seagate/cortx/pull/1383]

I am bit unsure linking following url to which QSG hyperlink. Can anyone help me in this?

[https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md]

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

 

PR raised: [https://github.com/Seagate/cortx/pull/1383]

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

@Rose Wambui,  this issue has been resolved. I request  you to please close this. I could not make changes to the status of the issue.

**Comment by mukul-seagate11** [comment]
Changed in https://github.com/Seagate/cortx/blob/main/QUICK_START.md so hence closing the issue

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Closed

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
