### ISSUE TITLE
google doc links need to migrate to sharepoint links

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#136]
1. https://github.com/Seagate/cortx/blob/master/doc/be/EOSS3IAMDD.rst#references

2. https://github.com/Seagate/cortx/blob/master/doc/be/CORTX-S3OVERVIEW.rst

search keyword google, you should see those three links

2a https://github.com/Seagate/cortx/blob/master/doc/be/CORTX-S3OVERVIEW.rst#cortx-s3-object-to-cortx-motr-object-mapping

2b https://github.com/Seagate/cortx/blob/master/doc/be/CORTX-S3OVERVIEW.rst#cortx-s3-metadata

2c https://github.com/Seagate/cortx/blob/master/doc/be/CORTX-S3OVERVIEW.rst#cortx-s3-apls-support

**Comment by johnbent** [comment]
Hey @Saumya-Sunder , @yoramnovick has reported that there are still some links in cortx/doc/architecture.md as well as cortx-motr/doc/motr-design-doc-list.rst.  Can you please help fix and notify us here when done?  Thanks!

**Comment by Saumya-Sunder** [comment]
Sure @johnbent I am on it.

**Comment by Saumya-Sunder** [comment]
Completed in PR# https://github.com/Seagate/cortx/pull/839

**Comment by mukul-seagate11** [comment]
Closing the issue as the same has been addressed in PR# 839
