### ISSUE TITLE
Images API Integration

### ISSUE THREAD

**Issue by hseow-seagate** [Seagate/cortx#1364]
[Images API](https://github.com/Seagate/cortx/tree/main/doc/integrations/images-api) integration seems to have some issue, the Dockerfile CMD uses `gunicorn` but the base image (or requirements.txt) doesn't contain this module.

I had to add `RUN pip install gunicorn` in the Dockerfile, however there are still issues related to `gunicorn`'s configuration where it seemingly runs the app twice, causing `address already in use` error. Unless you make the following changes in **api.py:**
```
if __name__ == '__main__':
    app.run()
```
There are also additional issues such as worker terminated due to timeout.

**On a side note:**
It also seems like you can't run the project on Windows as one of the module `pillow` doesn't seem to support Windows.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26906. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hseow-seagate** [comment]
I can't recall the exact error, but I remember that just by running `pip3 install -r requirements.txt` is not enough. Apparently you still need to install `gunicorn` and `image` (I think) as well.

IIRC, the initial error has something to do with this `ImportError: No module named PIL`, I also had this [page](https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil) in my browser history.

Additionally, there seems to be a need for an environment variable named `API_KEY` ([Step 0](https://github.com/Seagate/cortx/blob/main/doc/integrations/images-api/README.md)), which I have no idea what it's supposed to be. Skipping the variable doesn't cause immediate issue, but I haven't been able to run the application successfully.

I'm only able to open up a slow loading page that cannot resize images.

**Comment by hseow-seagate** [comment]
@r-wambui that looks great, I'll try it out this week (hopefully) and if all goes well, I'll close the issue.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Issue already closed on GitHub

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Issue already closed on Github
