### ISSUE TITLE
Create CORTX Components UML Diagram

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx#1405]
The current CORTX UML diagram is ugly and not up to date.

Objective of this issue is to create a UML Diagram of the different components of CORTX and how they interact with one another.

Current [CORTX components page](https://github.com/Seagate/cortx/blob/main/doc/Components.md)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28374. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by nrady** [comment]
@hessio I got this diagram from Cortx Exec review package. Not sure its usable or not ?

![image](https://user-images.githubusercontent.com/19796509/155461366-644e550a-86b5-4f69-a7c0-9f2cc40eedcf.png)

**Comment by johnbent** [comment]
Hello @nrady probably @ujjwalpl has the latest architectural diagram. When you create it, instead of UML can you please use Mermaid since that works natively with github markdown?

https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by johnbent** [comment]
Yeah, do whatever you think looks best. That mermaid is not very attractive for sure. :)

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

updated and merged per PR#1446

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

h1. Update CORTX UML Diagram #1446

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

h1. Update CORTX UML Diagram #1446
