### ISSUE TITLE
Create installation guide for CORTX on VirtualBox

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx#1407]
Currently there is a wiki for installing and running CORTX on VirtualBox. This guide has not been tested or reviewed in a long time and also it is not formatted cleanly.

The objective of this issue to reformat this wiki so it looks nice and that it works correctly.

Here is the link to the [Wiki](https://github.com/Seagate/cortx/wiki/CORTX-VM-on-VirtualBox)

VirtualBox is free software whereas VMWare is paid software that is why it is important to have this guide as well.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28376. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by alfhad** [comment]
@hessio I see the help wanted tag. I will take this up.

**Comment by alfhad** [comment]
@hessio I have tried the steps mentioned in the [document ](https://github.com/Seagate/cortx/wiki/CORTX-VM-on-VirtualBox) but I was stuck at the below step: 

```
Update network config scripts in /etc/init.d/network/scripts to add HWADDR lines to map the above to preferred names during udev rename_devices phase:
```
I tried modifying and creating network interface configuration file, but I was not able to change the interface names to ens*
IMHO the document needs to be modified for a better explanation and instruction of this step.

**Comment by hessio** [comment]
Hi @alfhad what is the error you are getting? Thanks for taking on this issue by the way :)

cc: @justinzw as he created this wiki

**Comment by alfhad** [comment]
Hey @hessio, there is a step in the doc which says to updated the network interface names to ens*, but there isn't a clear explanation to do so. 
I am not able to change the interface names to ens*, I need help with the same.

**Comment by hessio** [comment]
No longer relevant
