### ISSUE TITLE
Motr High-level designs two links are not valid

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#145]
**doc/hld/hld-template.rst.in** in **dev/architecture branch**

https://github.com/Seagate/cortx/blob/master/doc/SuggestedDocumentConversions.md#motr-high-level-designs

**Comment by johnbent** [comment]
@huanghua78 , have these been merged yet?

**Comment by johnbent** [comment]
@huanghua78 , I don't see 'doc/hld' in either cortx parent or cortx-motr repo.  Where should I be looking?  Do we still need to migrate them from "gerrit-dev/architecture" branch?  @mukul-seagate11 , have we not finished the migration?

**Comment by mukul-seagate11** [comment]
> @huanghua78 , I don't see 'doc/hld' in either cortx parent or cortx-motr repo. Where should I be looking? Do we still need to migrate them from "gerrit-dev/architecture" branch? @mukul-seagate11 , have we not finished the migration?

@johnbent, I can see the same in master_backup branch as, https://github.com/Seagate/cortx/blob/master_backup/doc/SuggestedDocumentConversions.md where links are broken so let me get that fixed in main

**Comment by huanghua78** [comment]
There is no "doc/hld/hld-template.rst.in in dev/architecture branch" in the doc.
This ticket can be closed.
