### ISSUE TITLE
AWS_EC2 Integration link

### ISSUE THREAD

**Issue by stx-hseow** [Seagate/cortx#1453]
There's a broken link in this [documentation](https://github.com/Seagate/cortx/tree/main/doc/integrations/AWS_EC2) =>

> To [create stable names for network interfaces](http://www.linuxfromscratch.org/lfs/view/6.3/chapter07/network.html) on the EC2 instance we will need to edit the `70-persistent-net.rules` file located here `/etc/udev/rules.d`

The best next link I could find is either [wiki.debian](https://wiki.debian.org/NetworkInterfaceNames#THE_.22PERSISTENT_NAMES.22_SCHEME) or [StackExchange](https://unix.stackexchange.com/a/75437).

Since I have never seen the original link (web page), I'm not sure what is the original reference is about.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29161. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by r-wambui** [comment]
@justinzw You are one of the contributors of the document referenced here
, could you please what the original link was meant to redirect to.

**Comment by r-wambui** [comment]
@stx-hseow I'm not very certain but I think the url has been changed to this : https://www.linuxfromscratch.org/lfs/view/9.0/chapter07/network.html

**Comment by stx-hseow** [comment]
That seems to be accurately relevant, would you update the documentation then?

**Comment by stx-hseow** [comment]
Closing this as PR is opened, and no longer an issue

**Comment by cortx-admin** [comment]
> Rose Wambui commented in Jira Server:

Closed on github

**Comment by cortx-admin** [comment]
> Rose Wambui commented in Jira Server:

Closed on github

**Comment by cortx-admin** [comment]
> Rose Wambui commented in Jira Server:

Closed on github
