### ISSUE TITLE
Unexpected character (']' (code 93)): expected a value

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1499]
#### Currently on:
+ **Commit**:  01f5b881af977d2b55391a1237186f4d9feb1127
+ **File**:    [doc/integrations/myDrive/tsconfig.json](https://github.com/Seagate/cortx/blob/01f5b881af977d2b55391a1237186f4d9feb1127/doc/integrations/myDrive/tsconfig.json)
+ **LineNum**: [77](https://github.com/Seagate/cortx/blob/01f5b881af977d2b55391a1237186f4d9feb1127/doc/integrations/myDrive/tsconfig.json#L77)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31096. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by nrady** [comment]
@mukul-seagate11 @r-wambui 
 The ']' character in Line#77 is the correct one.
The problematic line should be lLine#76 that should not have comma on the last element.

![image](https://user-images.githubusercontent.com/19796509/168771819-35dcb524-329d-4204-8a3c-d52ee30c29f2.png)

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

https://github.com/Seagate/cortx/issues/1499

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

Trailing comma bug  fix.

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

remove trailing comma per PR#1512

https://github.com/Seagate/cortx/pull/1512

**Comment by cortx-admin** [comment]
> Amnuay Boottrakoat commented in Jira Server:

fix trailing comma
