### ISSUE TITLE
[fenced-code-flag] Missing code language flag

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1524]
#### Currently on:
+ **Commit**:  6c26ac60bf5383f80b541e9cb579727b9f9353c6
+ **File**:    [doc/integrations/parlAI/docs/source/tutorial_torch_generator_agent.md](https://github.com/Seagate/cortx/blob/6c26ac60bf5383f80b541e9cb579727b9f9353c6/doc/integrations/parlAI/docs/source/tutorial_torch_generator_agent.md)
+ **LineNum**: [124](https://github.com/Seagate/cortx/blob/6c26ac60bf5383f80b541e9cb579727b9f9353c6/doc/integrations/parlAI/docs/source/tutorial_torch_generator_agent.md#L124)

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
