### ISSUE TITLE
[no-emphasis-as-heading] Don’t use emphasis to introduce a section, use a heading

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1526]
#### Currently on:
+ **Commit**:  97723172661ee8ac1542f2977bd92bd14e71d69d
+ **File**:    [doc/integrations/dvc/README.md](https://github.com/Seagate/cortx/blob/97723172661ee8ac1542f2977bd92bd14e71d69d/doc/integrations/dvc/README.md)
+ **LineNum**: [13](https://github.com/Seagate/cortx/blob/97723172661ee8ac1542f2977bd92bd14e71d69d/doc/integrations/dvc/README.md#L13)

**Comment by hessio** [comment]
Issue resolved on main branch
