### ISSUE TITLE
Unexpected unknown at-rule "@include" (at-rule-no-unknown)

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1530]
#### Currently on:
+ **Commit**:  119efa65721cdb86d32664a8333fe0e2e6c30d6a
+ **File**:    [doc/integrations/myDrive/public/fontawesome/scss/_screen-reader.scss](https://github.com/Seagate/cortx/blob/119efa65721cdb86d32664a8333fe0e2e6c30d6a/doc/integrations/myDrive/public/fontawesome/scss/_screen-reader.scss)
+ **LineNum**: [4](https://github.com/Seagate/cortx/blob/119efa65721cdb86d32664a8333fe0e2e6c30d6a/doc/integrations/myDrive/public/fontawesome/scss/_screen-reader.scss#L4)

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
