### ISSUE TITLE
Possible hardcoded secret key (secret)

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx#1547]
#### Currently on:
+ **Commit**:  86ee55d4efa91ffcbaf4a53c0af9267c0aad2175
+ **File**:    [doc/integrations/parlAI/application.py](https://github.com/Seagate/cortx/blob/86ee55d4efa91ffcbaf4a53c0af9267c0aad2175/doc/integrations/parlAI/application.py)
+ **LineNum**: [44](https://github.com/Seagate/cortx/blob/86ee55d4efa91ffcbaf4a53c0af9267c0aad2175/doc/integrations/parlAI/application.py#L44)

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Issue already fixed in code

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

issue fixed

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

.
