### ISSUE TITLE
Tiny completion in README 📜

### ISSUE THREAD

**Issue by 3lLobo** [Seagate/cortx#1582]
### Problem

Missing cmd when compared to prev version
https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-7/S3_IO_Operations.md
https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-6/S3_IO_Operations.md

v7:

- Validate and download the object from the bucket
```bash
aws s3 ls s3://mybucket/
```

v6:

- Validate and download the object from the bucket
```bash
aws s3 ls s3://mybucket/
aws s3 cp s3://mybucket/object file-download.txt
```

### Expected behavior

- Validate and download the object from the bucket
```bash
aws s3 ls s3://mybucket/
aws s3 cp s3://mybucket/object file-download.txt
```

### How to reproduce

Read: https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-7/S3_IO_Operations.md

### Deployment information

-

### Additional information

# 🦄

**Comment by cortx-admin** [comment]
> Rose Wambui commented in Jira Server:

- Closed on Github

**Comment by cortx-admin** [comment]
> Rose Wambui commented in Jira Server:

Closed on Github
