### ISSUE TITLE
Update the cortx-s3samplecode to work with the newer OVA versions

### ISSUE THREAD

**Issue by r-wambui** [Seagate/cortx#1628]
### Problem

The documentation on the [CORTX s3 sample code](https://github.com/Seagate/cortx/tree/main/cortx-s3samplecode); used for testing S3 API IO using various programming languages is outdated and does not work with the new OVA. Most of them are still structured to use the OVA with 3 network interfaces.

Example:
- During the hackathon, participants who followed the Node JS guide to make S3 IO ended up having a `InvalidLocationConstraint: The specified location constraint is not valid`
- There were also issues with the endpoint URL as users could not add the `port to access kubernetes cluster externally` to the endpoint url 

### Expected behavior

The endpoint URL for example should include the Kubernetes port

### How to reproduce

Set up OVA[ PI6](https://github.com/Seagate/cortx/tree/main/doc/ova/2.0.0/PI-6) or[ PI7](https://github.com/Seagate/cortx/tree/main/doc/ova/2.0.0/PI-7), then follow the documentation to test using either [Python](https://github.com/Seagate/cortx/tree/main/cortx-s3samplecode/python), [Node JS ](https://github.com/Seagate/cortx/tree/main/cortx-s3samplecode/node.js)etc

### Deployment information

VMware Workstation pro 16 pro

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33918. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
ova issues which are reported by community https://github.com/Seagate/cortx/issues?q=is%3Aopen+is%3Aissue+label%3Aova will be further raised to QA and tracked in next sprint.

**Comment by mukul-seagate11** [comment]
https://github.com/Seagate/cortx/pull/1657 is validated as per latest OVA image and no issue is observed
