### ISSUE TITLE
Completing s3 IO setup guide crashes OVA

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx#1630]
### Problem

I was following the steps outlined in the [IO setup guide](https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-7/S3_IO_Operations.md) associated with [OVA PI-7](https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-7/S3_IO_Operations.md) when following this guide I got to the testing section when I ran this [command](https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-7/S3_IO_Operations.md#:~:text=aws%20s3%20mb%20s3%3A//mybucket)  `aws s3 mb s3://mybucket` which just times out 

Also when I run \`hctl status\` command I get below error:

`[root@cortx-ova-rgw ~]# hctl status`

`Cluster is not running command terminated with exit code 1`

### Expected behavior

You should be able to run s3 commands and they should works

`hctl status` command should not terminate with exit code

### How to reproduce

Setup the OVA PI-7 and go through the s3 setup guide

### Deployment information

VMware Workstation 16 Pro

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33922. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by mukul-seagate11** [comment]
@hessio, OVA is still not tested on AWS and is in the roadmap

**Comment by hessio** [comment]
I was running this on VMWare but when I did the IO setup, the OVA stopped working completely, all commands would fail

**Comment by hessio** [comment]
The problem I faced was when I setup the OVA in VMWare Workstation `hctl status` command worked so cluster was running.

The next step in the process is to setup the s3 api endpoints and done this following the [this guide](https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-7/S3_IO_Operations.md) once I tried to test that these steps had worked correctly I faced an error trying to create a bucket and no s3 commands would work. 

So I tried the `hctl status` command to make sure the cluster was still running but instead I got this error:

`[root@cortx-ova-rgw ~]# hctl status`

`Cluster is not running command terminated with exit code 1`

**Comment by hessio** [comment]
I tried once again to verify issue - this time `hctl status` command completed but was showing services offline and s3 commands were not completing successfully.

```
[root@cortx-ova-rgw ~]# hctl status
Bytecount:
    critical : 0
    damaged : 0
    degraded : 0
    healthy : 0
Data pool:
    # fid name
    0x6f00000000000001:0x25 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x3b 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    cortx-server-headless-svc-cortx-ova-rgw
    [started]  hax                 0x7200000000000001:0x1d         inet:tcp:cortx-server-headless-svc-cortx-ova-rgw@22001
    [started]  rgw_s3              0x7200000000000001:0x20         inet:tcp:cortx-server-headless-svc-cortx-ova-rgw@21001
    cortx-data-headless-svc-cortx-ova-rgw  (RC)
    [offline]  hax                 0x7200000000000001:0x6          inet:tcp:cortx-data-headless-svc-cortx-ova-rgw@22001
    [offline]  ioservice           0x7200000000000001:0x9          inet:tcp:cortx-data-headless-svc-cortx-ova-rgw@21001
    [offline]  confd               0x7200000000000001:0x18         inet:tcp:cortx-data-headless-svc-cortx-ova-rgw@22002
[root@cortx-ova-rgw ~]#
```

Here is the output of `aws s3 ls`

```
[root@cortx-ova-rgw ~]# aws s3 ls

Could not connect to the endpoint URL: "http://10.100.43.117:80/"
```

**Comment by hessio** [comment]
ova issues which are reported by community https://github.com/Seagate/cortx/issues?q=is%3Aopen+is%3Aissue+label%3Aova will be further raised to QA and tracked in next sprint.

**Comment by hessio** [comment]
issue is still relevant for PI-7 but doesn't seem to appear in PI-8. cc: @mukul-seagate11

**Comment by mukul-seagate11** [comment]
> issue is still relevant for PI-7 but doesn't seem to appear in PI-8. cc: @mukul-seagate11

@hessio, you can refer the exit criteria and validations logs of PI-7 OVA in https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/1036517377/PI-7+Test+Entry+Criteria+Dev+RE+Validation

**Comment by mukul-seagate11** [comment]
https://github.com/Seagate/cortx/pull/1657 is validated as per latest OVA image and no issue is observed
