### ISSUE TITLE
OVA 2.0.0 - 790 issue with Fusion (on Mac)

### ISSUE THREAD

**Issue by sainarasim** [Seagate/cortx#1634]
### Problem

Once the OVA boots and the network is up, hctl status takes indefinite time time to complete, or just throws an error.

### Expected behavior

hctl status needs to complete in 5-10 mins

### How to reproduce

Start VM,
 start networking on VM, 
hctl status
[ Just hangs or throws an error]

#hctl status
Unable to connect to the server: dial tcp 10.230.242.76:6443: i/o timeout
error: pod, type/name or --filename must be specified

### Deployment information

VMWARE Fusion - Professional Version 12.0.0 (16880131)
Host: MacOS Catalina 10.15.7
OVA: https://github.com/Seagate/cortx/blob/main/doc/ova/2.0.0/PI-7/CORTX_on_Open_Virtual_Appliance_PI-7.rst

### Additional information

There was only one instance when it did come up  out of many tests

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33985. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
@mukul-seagate11 please see issue faced by user when trying to use OVA on MacOS and VMWare Fusion

**Comment by hessio** [comment]
When working with @sainarasim on debugging there was a time when the OVA started fine first time and there were times when hctl status would take much longer than 30 minutes before you could use it. 

The other issue faced by @sainarasim was when he tried connect to the OVA he got RequestTimeTooSkewed error where he had to set the timezone and the time to be the same as the timezone and time he was in physically.

**Comment by hessio** [comment]
ova issues which are reported by community https://github.com/Seagate/cortx/issues?q=is%3Aopen+is%3Aissue+label%3Aova will be further raised to QA and tracked in next sprint.

**Comment by hessio** [comment]
@mukul-seagate11 do we have someone with a Mac to verify if this issue is present on the new OVA?

**Comment by mukul-seagate11** [comment]
> @mukul-seagate11 do we have someone with a Mac to verify if this issue is present on the new OVA?

CC @pranav-sahasrabudhe

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
