### ISSUE TITLE
Long Term Goal for Building CORTX

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#204]
@shailesh-vaidya , eventually there should be a build script in this parent repo so after doing a recursive clone of all the sub-repos, that there is a 'Makefile' or whatever in this parent repo so that people can just do:
> git clone -r cortx
> ./configure
> make
Or something like that.

**Comment by shailesh-vaidya** [comment]
We have published docker image to build entire CORTX at https://github.com/orgs/Seagate/packages/container/package/cortx-build 
Instructions to build CORTX packages using this Docker image is documented at - https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst

**Comment by shailesh-vaidya** [comment]
@andriytk  @johnbent 

We have published docker image to build entire CORTX at https://github.com/orgs/Seagate/packages/container/package/cortx-build

Instructions to build CORTX packages using this Docker image is documented at - https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst

Can we close this issue.

**Comment by shailesh-vaidya** [comment]
@johnbent  Could you please confirm if we can close this issue.

**Comment by johnbent** [comment]
@shailesh-vaidya , we are waiting for @hessio to reproduce this.  Also, we need the instructions for how to _run_ the software after it has been built.  I guess it is OK to close this and then have Patrick re-open if there are problems.  What about instructions for how to run it after it has been built?  Does that exist anywhere?

**Comment by shailesh-vaidya** [comment]
@johnbent  - Sure. @hessio  Let me know if you face any issues. 
We can use following docs to _run_ software after Release build is generated.  These docs are from Provisioning Team to deploy CORTX stack. However need to verify it once using Release build generated from docker image. 
VM - https://github.com/Seagate/cortx-prvsnr/wiki/Auto-Deploy-VM-Provisioner-CLI-Commands
Hardware - https://github.com/Seagate/cortx-prvsnr/wiki/Auto-Deploy-Provisioner-CLI-Commands
