### ISSUE TITLE
Github Issues Page - "Want to contribute?" section.

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx#243]
Most open source repos have a "Want to Contribute" section in their Github issues page.

Example:

https://github.com/rails/rails/issues

![image](https://user-images.githubusercontent.com/950172/92687135-d6055280-f2ef-11ea-8a1e-b78b92c1f3f6.png)

https://github.com/atom/atom/issues
https://github.com/twbs/bootstrap/issues

I think it's helpful to have but I can't figure out how to add this to our page.

 @johnbent @novium258 @amolkongre  @mukul-seagate11  what do you think about adding this?
Also any idea on how we can add/configure this?

@xahmad Some other Seagate repos like -> https://github.com/Seagate/openSeaChest have it too. Do you know how they configured it?

**Comment by callahad** [comment]
I think it's based on the presence of a `CONTRIBUTING.md` for the first line and, traditionally, having a label literally named `good first issue` for the second. So I _do_ see a partial contributing banner on the issues page:

![2020-09-30_22-28](https://user-images.githubusercontent.com/24193/94741624-4f7ee680-036c-11eb-8859-ad7cefb12d94.png)

About a year ago GitHub began [using machine learning](https://github.blog/2020-01-22-how-we-built-good-first-issues/) to augment the list of good first issues, but it's not a replacement for manual labeling.

See https://github.com/Seagate/cortx/contribue for what GitHub has identified as beginner friendly.

**Comment by johnbent** [comment]
https://support.github.com/ticket/personal/0/856384 <- asked Enterprise support about this
