### ISSUE TITLE
Improve new issues experience/ Issue Template

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx#247]
When a user files a new issue, there needs to be an Issue Template that can guide them and also it would be nice to have a "guide" on the right hand side like the example below:

Example:

https://github.com/minio/minio/issues/new?assignees=&labels=community%2C+triage&template=bug_report.md&title=

![image](https://user-images.githubusercontent.com/950172/92737172-c3127280-f32f-11ea-8ce5-e14226608cdc.png)

Minio Issue Template: https://github.com/minio/minio/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by johnbent** [comment]
Looks like there is an easy automated way to turn this on.  A repo admin can go into repo settings and see this:

![image](https://user-images.githubusercontent.com/2047294/94195724-9ce0ec80-fe70-11ea-8e11-887b475badb3.png)

See how it says, "Setup Templates" in the green button?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you create the issue template as suggested?

**Comment by Saumya-Sunder** [comment]
@mukul-seagate11 we had decided that @justinzw will manage this. @justinzw I think we have updated the issue template right?

**Comment by mukul-seagate11** [comment]
@justinzw, Will you be taking care of this issue?

**Comment by mukul-seagate11** [comment]
This issue has been resolved
