### ISSUE TITLE
Instructions are not clear in 'Deploying a VM'

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#256]
https://github.com/Seagate/cortx/blob/main/doc/Deploying%20a%20VM.rst

@VenkyOS , these instructions are not clear.  The instructions need to be very clear and easy to follow.  For example, I have absolutely zero idea what this means: "Pop-ups from ESX server must be allowed."

Also, the filename should not contain spaces.

**Comment by VenkyOS** [comment]
This document does not exist.
