### ISSUE TITLE
Internal links in LocalVMSetup.md

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#257]
@shailesh-vaidya , there is an internal link here:
https://github.com/Seagate/cortx/blob/main/doc/LocalVMSetup.md
Can we copy those those files into a release and then change this file to reference the files from their new location?

If not you, can someone else please help with this?

**Comment by shailesh-vaidya** [comment]
@Saumya-Sunder  I feel we have fixed all internal links by now.  Could you please point me if there are any location with internal links. I will take a look.

**Comment by Saumya-Sunder** [comment]
Hey @shailesh-vaidya this is an old file, marked for deletion : https://github.com/Seagate/cortx/blob/main/doc/LocalVMSetup.md. We've only kept it on because it might be linked on other docs. I am adding the link to the new doc at the top of this doc so that contributors can access the correct article if they land here.

**Comment by shailesh-vaidya** [comment]
@Saumya-Sunder Could you please take a look if this issue still persists.

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you update?

**Comment by Saumya-Sunder** [comment]
@mukul-seagate11 this is an old file, I need to create a new document for setting up single node VM. Any VM that is on a local instance is single node as per one SME, I forget their name. So what is the correct approach here? I am going around in circles, please route me to one person who can point me to a KB or a doc

**Comment by u-u-h** [comment]
I see cortx-storage.colo.seagate.com referenced in https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md, and that is a domain not accessible for end users like me. Any hints on how to which repos can be used for self-construction of VMs?

**Comment by shailesh-vaidya** [comment]
@u-u-h  Thanks for reaching out. We are in-process of updating [Cluster_Setup.md](https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md) with details.

We have published docker image to build entire CORTX . Instructions to build CORTX packages using this Docker image is documented at - https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst 

You can try that out to build CORTX packages on your VM.

**Comment by shailesh-vaidya** [comment]
@u-u-h Just want to touch base with you if you get chance to build entire CORTX using Docker image . Instructions to build CORTX packages using this Docker image is documented at - https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst

Let us know if you face any issues.

**Comment by mukul-seagate11** [comment]
Do we have any update on this issue or can be closed?

**Comment by mukul-seagate11** [comment]
As we see no update on the issue after reminder so closing the same accordingly, 
please feel free to reopen the issue if you encounter any issue
