### ISSUE TITLE
https://github.com/Seagate/cortx/blob/main/README.md suggestions

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#258]
![image](https://user-images.githubusercontent.com/68423216/92984339-04e01c00-f4dc-11ea-805e-457c38433c6d.png)

merge and combine A to B

![image](https://user-images.githubusercontent.com/68423216/92984463-dca4ed00-f4dc-11ea-98ae-01cc506e8b9d.png)
where this image comes from? 1. it seems to contradict to the public info: https://www.seagate.com/files/www-content/our-story/trends/files/dataage-idc-report-final.pdf; 2. 17ZB stored, how come we have 158ZB at risk in 2025?

**Comment by Saumya-Sunder** [comment]
Resolved in CORTX CONTRIBUTING.md file
