### ISSUE TITLE
https://github.com/Seagate/cortx/blob/main/doc/CORTXContributionGuide.md suggestions

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#259]
![image](https://user-images.githubusercontent.com/68423216/92984655-55f10f80-f4de-11ea-8f78-98975a55b63b.png)

![image](https://user-images.githubusercontent.com/68423216/92984720-dadc2900-f4de-11ea-9da1-bdedf890fa94.png)
A can link to https://github.com/Seagate/cortx/blob/main/doc/SSH%20Public%20Key.rst

![image](https://user-images.githubusercontent.com/68423216/92984773-56d67100-f4df-11ea-8799-4025c4b51e46.png)

**Comment by Saumya-Sunder** [comment]
Resolved in the CORTX CONTRIBUTING.md file
