### ISSUE TITLE
hctl bootstrap --mkfs singlenode.yaml failed

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#266]
installed cortx-motr and cortx-hare.

> [root@ssc-vm-1091 examples]# hctl bootstrap --mkfs singlenode.yaml
> 2020-09-12 22:33:38: Generating cluster configuration... OK
> 2020-09-12 22:33:39: Starting Consul server agent on this node............ OK
> 2020-09-12 22:33:49: Importing configuration into the KV store... OK
> 2020-09-12 22:33:49: Starting Consul agents on other cluster nodes... OK
> 2020-09-12 22:33:49: Updating Consul agents configs from the KV store... OK
> 2020-09-12 22:33:50: Installing Motr configuration files... OK
> 2020-09-12 22:33:50: Waiting for the RC Leader to get elected...... OK
> 2020-09-12 22:33:53: Starting Motr (phase1, mkfs)...Job for motr-mkfs@0x7200000000000001:0x9.service failed because the control process exited with error code. See "systemctl status motr-mkfs@0x7200000000000001:0x9.service" and "journalctl -xe" for details.
> [root@ssc-vm-1091 examples]# journalctl -xe
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com systemd[1]: start request repeated too quickly for hare-hax.service
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com systemd[1]: Failed to start HAX daemon for Hare.
> -- Subject: Unit hare-hax.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit hare-hax.service has failed.
> --
> -- The result is failed.
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com systemd[1]: Unit hare-hax.service entered failed state.
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com systemd[1]: hare-hax.service failed.
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com hare-consul[2767]: 2020-09-12T22:34:00.397-0600 [WARN]  agent: Check is now critical: check=service:
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com hare-consul[2767]: 2020-09-12T22:34:00.399-0600 [INFO]  agent: Synced check: check=service:6
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com sudo[4159]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/mkdir -p /var/log/hare
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com systemd[1]: Created slice User Slice of root.
> -- Subject: Unit user-0.slice has finished start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit user-0.slice has finished starting up.
> --
> -- The start-up result is done.
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com systemd[1]: Started Session c3 of user root.
> -- Subject: Unit session-c3.scope has finished start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit session-c3.scope has finished starting up.
> --
> -- The start-up result is done.
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com sudo[4159]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com sudo[4159]: pam_unix(sudo:session): session closed for user root
> Sep 12 22:34:00 ssc-vm-1091.colo.seagate.com systemd[1]: Removed slice User Slice of root.
> -- Subject: Unit user-0.slice has finished shutting down
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit user-0.slice has finished shutting down.
> Sep 12 22:34:01 ssc-vm-1091.colo.seagate.com hare-consul[2767]: 2020-09-12T22:34:01.406-0600 [WARN]  agent: Check is now critical: check=service:
> Sep 12 22:34:02 ssc-vm-1091.colo.seagate.com hare-consul[2767]: 2020-09-12T22:34:02.415-0600 [WARN]  agent: Check is now critical: check=service:
> Sep 12 22:34:02 ssc-vm-1091.colo.seagate.com hare-consul[2767]: 2020-09-12T22:34:02.610-0600 [ERROR] agent.http: Request error: method=PUT url=/v
> 
> [root@ssc-vm-1091 examples]# systemctl status motr-mkfs@0x7200000000000001:0x9.service
> ● motr-mkfs@0x7200000000000001:0x9.service - Motr mkfs helper for 0x7200000000000001:0x9 service
>    Loaded: loaded (/usr/lib/systemd/system/motr-mkfs@.service; static; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Sat 2020-09-12 22:33:55 MDT; 2min 34s ago
>   Process: 3852 ExecStart=/usr/libexec/cortx-motr/motr-mkfs %i (code=exited, status=42)
>  Main PID: 3852 (code=exited, status=42)
> 
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com motr-mkfs[3852]: + exec /var/cortx/cortx-motr/utils/mkfs/m0mkfs -e lnet:10.230.247.138@tcp:...934592
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com motr-mkfs[3852]: motr[03855]:  ec60  ERROR  [net/lnet/ulnet_core.c:1177:nlx_core_tm_start]  <! rc=-2
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com motr-mkfs[3852]: motr[03855]:  a680  ERROR  [rpc/rpc_machine.c:506:rpc_tm_setup]  <! rc=-10... start
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com motr-mkfs[3852]: motr[03855]:  a680  ERROR  [rpc/rpc_machine.c:172:m0_rpc_machine_init]  <! rc=-101
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com motr-mkfs[3852]: propagating error to parent shell
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com motr-mkfs[3852]: got sub-shell error, terminating..
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com systemd[1]: motr-mkfs@0x7200000000000001:0x9.service: main process exited, code=exited, sta...42/n/a
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com systemd[1]: Failed to start Motr mkfs helper for 0x7200000000000001:0x9 service.
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com systemd[1]: Unit motr-mkfs@0x7200000000000001:0x9.service entered failed state.
> Sep 12 22:33:55 ssc-vm-1091.colo.seagate.com systemd[1]: motr-mkfs@0x7200000000000001:0x9.service failed.
> Hint: Some lines were ellipsized, use -l to show in full.

**Comment by johnbent** [comment]
@yanqingfu , by the way, where did you find a link to https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md?  Those instructions are very specific to internal Seagate and won't work for the community so we should figure out how it is reachable and either remove the link or we should update the instructions so that they work for community members.

**Comment by yanqingfu** [comment]
@johnbent https://github.com/Seagate/cortx/blob/main/doc/VIRTUAL_MACHINE.md#testing-the-cluster

https://github.com/Seagate/cortx/blob/main/doc/VIRTUAL_MACHINE.md seems didn't link to anywhere

**Comment by mukul-seagate11** [comment]
@madhavemuri @sachitanands, please assist to address the issue or route to the concern person

**Comment by madhavemuri** [comment]
This issue is resolved already.
I think this can be closed.
