### ISSUE TITLE
Virtual Appliance EULA

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#275]
@VenkyOS , when you create the document explaining how to download the use the VA, please do the following as directed by @pmbickley and @gregnsk:

1. Do not create a direct link to the OVA file
2. Instead, create an indirect link
3. Wherever you say, "Click HERE to download the OVA file," or whatever comparable language you use, HERE should be a link to a file called 'va_eulu.rst'
4. va_eula.rst should have some introductory text and then at the bottom of the page, you can finally have the direct link to the OVA

The text in va_eula.rst should say,

"CORTX is happy to provide the virtual machine image for the convenience of the community to test the CORTX software.  Please read this entire file before using the link at the bottom of this page to download the image.  This image is provided merely for testing purposes and is not a supported Seagate product.  Users should use this image only for testing purposes and should not store any critical data on it.

After reading the above, please download the image HERE"

Thanks,

John

**Comment by VenkyOS** [comment]
This issue is fixed.
