### ISSUE TITLE
stalebot is closing issues

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#288]
https://github.com/Seagate/cortx-prvsnr/issues/283
![image](https://user-images.githubusercontent.com/2047294/93432838-4fb6b680-f883-11ea-9fa4-cab2bc4c46fe.png)

@gauravchaudhari02 @mukul-seagate11 @shailesh-vaidya @amolkongre  , can one of you please assign someone to fix this?  Thanks!

**Comment by shailesh-vaidya** [comment]
@gauravchaudhari02 @mukul-seagate11  AFAIK we have validated that adding `daysUntilClose: false` fix auto closing issue.  We may start enabling stale bot for repositories.

**Comment by gauravchaudhari02** [comment]
>@gauravchaudhari02 @mukul-seagate11 AFAIK we have validated that adding daysUntilClose: false fix auto-closing issue. We may start enabling stale bot for repositories.

Its been taken care of. Closing this issue. Please reopen if you see this phenomenon again.
