### ISSUE TITLE
Document Confusion

### ISSUE THREAD

**Issue by PengMacro** [Seagate/cortx#296]
I am following [this ](https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md#12-install-the-rpms)to install hare rpms but got the below error. I solved it by [building hare rpms locally instead](https://github.com/Seagate/cortx-hare/blob/dev/README.md#installation). I think that's because my VM is not within seagate. Maybe revising related document is needed. 

![image](https://user-images.githubusercontent.com/37490734/93412182-46692200-f862-11ea-846b-60d885147d1b.png)

Also, [Hare Developer Guide](https://github.com/Seagate/cortx-hare/blob/dev/README_developers.md#installation), [Hare User Guide](https://github.com/Seagate/cortx-hare/blob/dev/README.md#hare-user-guide) and [cluster-setup](https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md#1-single-node-setup) contain duplicated and minor different content. I suggest updating or merging those files.

**Comment by shailesh-vaidya** [comment]
@Saumya-Sunder  
http://cortx-storage.colo.seagate.com/releases/ links will not be accessible from outside. Hence we need to put alternative for that in document. 
Also [Create a VM](https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md#1-single-node-setup) will not be applicable.

**Comment by mukul-seagate11** [comment]
@shailesh-vaidya, I do understand that this cannot be accessible from outside but cant we implement the same as we had build the CORTX packages locally using Docker Image for external community as a solution?

**Comment by shailesh-vaidya** [comment]
@mukul-seagate11  - Yes.  Docker image to build CORTX outside Seagate is ready and currently under testing and docuementaion phase. Details are available at https://github.com/Seagate/cortx-re/issues/167 

For this issue - We should include steps to build Motr, Hare before using them. Following links can be added with consultation of respective component teams. 
Hare - https://github.com/Seagate/cortx-hare/blob/dev/README.md#installation 
Motr - https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst

**Comment by mukul-seagate11** [comment]
@PengMacro, So as suggested, Docker image to build CORTX for external community is ready and currently under testing and documentation phase so hope we are good to close the issue?
