### ISSUE TITLE
Contribution Guides should be called root/CONTRIBUTING.md

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#310]
All of our repos should have a root/CONTRIBUTING.md file as that is a special file name that github recognizes and treats specially like it does README.md and LICENSE.md.  More info here: https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file.

We have contributing guides for each repo but they aren't in the proper location with the proper name.  For example, https://github.com/Seagate/cortx-s3server/blob/dev/docs/ContributingToCortxS3.md should be renamed and moved to the root.  And any and all links to it should be changed.

@Saumya-Sunder , can you handle this please?

**Comment by Saumya-Sunder** [comment]
Closing this as it's done
