### ISSUE TITLE
Github : Secret Audit

### ISSUE THREAD

**Issue by gowthamchinna** [Seagate/cortx#312]
Audit Seagate GitHub repo's for GITHUB tokens and other org credentials.

Ref : 

- https://docs.github.com/en/github/administering-a-repository/about-secret-scanning
- https://github.com/features/security/advanced-security/signup
- https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository
- https://securitytrails.com/blog/github-dorks

Github Action:
- https://github.com/marketplace/actions/secret-scan

**Comment by mukul-seagate11** [comment]
let me check & update

**Comment by mukul-seagate11** [comment]
Will test & implement via https://github.com/Seagate/cortx/security for repos as the feature is now GA
