### ISSUE TITLE
Automatically find broken links

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#350]
It would be cool to have a tool that automatically finds any broken links in our documentation.  This looks like it might work:

https://github.com/marketplace/actions/broken-link-check

Does it also find orphaned docs that aren’t reachable?

**Comment by gauravchaudhari02** [comment]
@Saumya-Sunder, I guess you were trying to write a GitHub Action for this right?

**Comment by Saumya-Sunder** [comment]
Yes, but the separate install steps did not work. I can sit with you and let you know where I got stuck. Maybe we can close it faster @gauravchaudhari02

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you work with @gauravchaudhari02 and close the same?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, please update & close accordingly

**Comment by mukul-seagate11** [comment]
As there is no update, hence closing the issue
