### ISSUE TITLE
Add SAGE history to the FAQ

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#371]
Also, I found it sad to read that this comes from an EU funded project but no mention of that project. It's nice to see something practical come out of i.e. H2020, but one would like to know more.

_Originally posted by @FlorianHeigl in https://github.com/Seagate/cortx/discussions/369_

Some links that might be useful:
https://www.hpcwire.com/2016/11/29/seagate-led-sage-project-delivers-update-exascale/
https://www.seagate.com/news/news-archive/seagates-joins-historic-european-commission-master-pr/

**Comment by huanghua78** [comment]
There is a doc to talk about the EU H2020 project:

doc/be/CORTX_TUTORIAL.rst

**Comment by johnbent** [comment]
Thanks @huanghua78 , yes, the answer in the FAQ should include a link to that document as well.

**Comment by johnbent** [comment]
Hey @sainarasim , can you take this one please?

**Comment by johnbent** [comment]
This was fixed by Sai.  Thanks Sai.
