### ISSUE TITLE
Add motr-in-prose to the FAQ

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#377]
Thanks @zacharywhitley , good for you for digging around and finding that!  Yes, for people, clearly like yourself, who like deep technical information, I agree with you that the [motr-in-prose.md](https://github.com/Seagate/cortx-motr/blob/main/doc/motr-in-prose.md) is currently our best document.  I'll create an issue that we should add this to our FAQ to make it more obvious so that the next person doesn't have to do the same amount of digging that you did.

ANSWER: https://github.com/Seagate/cortx-motr/blob/main/doc/motr-in-prose.md is probably currently the best document to really help answer the question about 'What is CORTX?'.

_Originally posted by @johnbent in https://github.com/Seagate/cortx/discussions/376#discussioncomment-86226_

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you update & fix

**Comment by Saumya-Sunder** [comment]
Done [here](https://github.com/Seagate/cortx/pull/506) @mukul-seagate11 . closing this issue.
