### ISSUE TITLE
Installing Dependencies Error

### ISSUE THREAD

**Issue by PengMacro** [Seagate/cortx#383]
I am following [this](https://github.com/Seagate/cortx/blob/main/doc/InstallingDependencies.md#installing-dependencies) and got "bash: githubrelease: command not found" when I ran "githubrelease" command.

I tried to use pip instead of pip3 to [install ](https://pypi.org/project/githubrelease/)it and it works.

**Comment by PengMacro** [comment]
Then I got the below error:
![image](https://user-images.githubusercontent.com/37490734/94913084-40805d00-046e-11eb-82a7-a9203cb1b747.png)


Also, I wonder do we really need step1? (considering we have "githubrelease download" command in step2) If so, how to download it? use "curl" command?
![image](https://user-images.githubusercontent.com/37490734/94912816-d7004e80-046d-11eb-8935-448d7436723e.png)

**Comment by mukul-seagate11** [comment]
Actually step 1 is to download & install CORTX Build Dependencies related to binaries packages where step 2 is installing githubrelease binary package so both are two separate steps

**Comment by shailesh-vaidya** [comment]
From error message looks like variable GITHUB_TOKEN does not have proper value. below command should print your token.
`echo $GITHUB_TOKEN `   
If not please execute,  
`export GITHUB_TOKEN=<YOUR GITHUB TOKEN>` 
`githubrelease --github-token $GITHUB_TOKEN  asset Seagate/cortx download build-dependencies`

**Comment by PengMacro** [comment]
@shailesh-vaidya 
I have configured my github token but still got the error. By the way, I installed githubrelease using pip instead of pip3 since the pip3 version did not work for me.
![image](https://user-images.githubusercontent.com/37490734/94981461-2d19d400-04f8-11eb-86a1-14fd5ecf51b8.png)

**Comment by PengMacro** [comment]
@mukul-seagate11 
I see. Could you tell me exactly how should I download & install CORTX Build Dependencies? Should I download every rpm below and manually install them using "yum localinstall" command? 
![image](https://user-images.githubusercontent.com/37490734/94982490-779f4e80-0500-11eb-8f7e-e934661de56a.png)

**Comment by shailesh-vaidya** [comment]
> @shailesh-vaidya
> I have configured my github token but still got the error. By the way, I installed githubrelease using pip instead of pip3 since the pip3 version did not work for me.
> ![image](https://user-images.githubusercontent.com/37490734/94981461-2d19d400-04f8-11eb-86a1-14fd5ecf51b8.png)

@PengMacro  -  error message looks different from earlier one. Current one seems to be bash PATH related issue. By default `githubrelease` command is installed at `/usr/local/bin/githubrelease` . Can you check if its available, 

```
[root@localhost ~]# which githubrelease
/usr/local/bin/githubrelease
[root@localhost ~]# echo $PATH
/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
[root@localhost ~]#
```
Installing from pip or pip3 should not cause any issue. However please let us know issue with pip3 installation. We can check what's causing problem.

**Comment by PengMacro** [comment]
If I use pip3 to install githubrelease, it is not working (caused above error).
Here is the output:
```
[root@node1 cortx-build-dependencies]# which githubrelease
/usr/bin/which: no githubrelease in (/sbin:/bin:/usr/sbin:/usr/bin)
[root@node1 cortx-build-dependencies]# echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin
```

If I use pip to install it, it works. 
```
[root@node1 cortx-build-dependencies]# which githubrelease
/bin/githubrelease
```

Also, do you know what should I do for [step1](https://github.com/Seagate/cortx/blob/main/doc/InstallingDependencies.md)? I remembered I skipped this step before and both motr and s3server are working properly.

**Comment by shailesh-vaidya** [comment]
@PengMacro  Ok. So hope issue with `githubrelease ` command is resolved and you are able to download packages using mentioned steps. Let us know if issue still there. 

We need to install various dependency packages while building CORTX components. [steps#1](https://github.com/Seagate/cortx/blob/main/doc/InstallingDependencies.md#installing-dependencies) ensures that you have yum repository configured on your system to install any of dependency package. Hence during component build process you can easily install them through `yum` command. You can follow steps for each component to build respective component packages.  Let us know if you face any issues. in that.

**Comment by PengMacro** [comment]
Thanks for the help!
