### ISSUE TITLE
doc/be has some good docs

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#385]
doc/be has some good docs but many of them seem like they should be migrated to children repos and all of them need to be reachable from existing documentation.

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you update on the issue?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, please update & close accordingly

**Comment by mukul-seagate11** [comment]
As there is no update, hence closing the issue
