### ISSUE TITLE
Unable to connect to https://<management IP>:28100/#/preboarding/welcome

### ISSUE THREAD

**Issue by kevin-a-nelson** [Seagate/cortx#387]
OS: macOS Catalina 10.15.7
Hypervisor: VMware Fusion Professional Version 12.0.0

Steps to reproduce:

**1. Follow the onboarding process in the link below until step 9.**

https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst

**2. Get the management IP**

<img width="1103" alt="Screen Shot 2020-10-05 at 8 50 41 PM" src="https://user-images.githubusercontent.com/45378834/95150020-e83aab00-074c-11eb-8cef-99d466194543.png">

**3. Go to https://\<management IP\>:28100/#/preboarding/welcome**

Since my management IP was 10.44.152.96 I went to 

https://10.44.152.96:28100/#/preboarding/welcome

At this point I get a "This site can't be reached" 

<img width="1440" alt="Screen Shot 2020-10-05 at 8 58 04 PM" src="https://user-images.githubusercontent.com/45378834/95150309-8890cf80-074d-11eb-8541-4809b5e5256a.png">

**Comment by johnbent** [comment]
Hey Kevin,

Thanks for reporting this!  @justinzw has been working to replicate this.  Unfortunately, we don't have great access to Mac so our testing on Mac was not as good as it should have been.  By the way, there is also lots of discussion happening about this in Slack as well as in https://github.com/Seagate/cortx/discussions/379.

Please let us know if you figure this out or rest assured that we'll let you know as soon as we figure it out!  👍 

Thanks

**Comment by justinzw** [comment]
Thanks @kevin-a-nelson I'm able to reproduce this issue on my mac and am following up with VMware to understand whether this might be VMware Fusion blocking that port.

**Comment by fyqphd** [comment]
could you try use Safari browser？when I use google chrome, couldn't open

**Comment by Saumya-Sunder** [comment]
Hey @justinzw have you made any progress on this issue? I would like to link it to the file as a resolved issue.

**Comment by mukul-seagate11** [comment]
@justinzw, can you update on the issue or assign to the concern person?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, hope this issue is duplicate & resolved already addressed on 19/12 correct?

**Comment by mukul-seagate11** [comment]
Issue has been fixed & documented in https://github.com/Seagate/cortx/blob/main/doc/Preboarding_and_Onboarding.rst

![image](https://user-images.githubusercontent.com/65269273/103200429-52f61f80-4913-11eb-8c07-353d0bfde825.png)
