### ISSUE TITLE
OVA 1.0.1 has changed and now the documentation is broken

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#397]
1.0.1 has been changed in https://github.com/Seagate/cortx/releases/tag/VA and now our documentation in https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst is broken.

Specifically, there is no cortx/opensource! user/password as is specified in step 3 of the instructions.

**Comment by johnbent** [comment]
Thanks to @ImSoGoofy  for reporting this!

**Comment by pradeep-gothoskar** [comment]
@johnbent  - Shouldn't this be assigned to Venky - who can update the documentation ? 
Or is the Ova CORTx functionality is broken ?

**Comment by shailesh-vaidya** [comment]
Artifacts uploaded to https://github.com/Seagate/cortx/releases/tag/VA is not changed.  Tested with downloading artifacts and verified sha256sum. 

```
[root@localhost root]# githubrelease --github-token $GITHUB_TOKEN asset seagate/cortx download VA
release VA: downloading cortx-va-1.0.0.zip
  [####################################]  1.78G/1.78G  100%  cortx-va-1.0.0.zip
release VA: downloading cortx-va-1.0.1.zip
  [####################################]  1.88G/1.88G  100%  cortx-va-1.0.1.zip
[root@localhost  root]# sha256sum cortx-va-1.0.0.zip
2d92e0f190fcefb3789b7b64bc215e4e8fb5fb3b7872fa90bd964bf48c0bf60c  cortx-va-1.0.0.zip
[root@localhost root]# sha256sum cortx-va-1.0.1.zip
0a58424aae37a28260f7a75aa4324c085cbacb073428a86c0522bfb78c14df6d  cortx-va-1.0.1.zip
```

**Comment by mukul-seagate11** [comment]
@all, there is no change from credentials as well as documentation perspective as,

![image](https://user-images.githubusercontent.com/65269273/95825698-e7a6a380-0d4e-11eb-9a25-51669f7e6d88.png)

**Comment by justinzw** [comment]
Closing issue because it doesn't seem to occur as reported.
