### ISSUE TITLE
ldap admin password in VM vapp

### ISSUE THREAD

**Issue by korenlev** [Seagate/cortx#423]
hi
# ldap admin used by apps to update ldap data
dn: cn=sgiamadmin,dc=seagate,dc=com

what is the default password, where is this documented please ?

**Comment by sachitanands** [comment]
Hi @korenlev 
ldap password is set during ansible script of s3server (<cortx-s3server>/scripts/dev/init.sh) 
this password was taken from user as mentioned in [Setup document](https://github.com/Seagate/cortx-s3server/blob/dev/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#12-installing-dependencies) (pls check "**_Before you begin_**" section) e.g "Enter new password for openldap IAM admin: ldapadmin"

If you already ran s3server init.sh script then you can also get the configured ldap password from below file /root/.s3_ldap_cred_cache.conf (ldap_admin_pwd=<your-password>)

If you want to setup new password then pls re-run init.sh script and specify input parameter during this execution.
Note after init.sh run you need to run jenkins-build.sh script as well

**Comment by korenlev** [comment]
perfect , thanks much @sachitanands for the info, let's close issue
