### ISSUE TITLE
Videos file in github

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#428]
@Saumya-Sunder , can you please create a nice github page for us where we list all of our videos?  It basically just needs to be another view into the videos that we have in our youtube channel: https://www.youtube.com/playlist?list=PLOLUar3XSz2M_w5OxQLNDBTpSrsGbjDWr.

Can you make it be a nice list ordered by most recent at the top and have for each video the following:
* thumbnail image
* title
* date
* speaker(s)
* 1-2 sentence description

Also at the top have a link to the youtube channel.  And it SUPPORT.md and README.md where we have the link to youtube also please change those lines to say something like:
* Check out our <video page> which shows the videos which are also available in our <youtube channel>

If you don't have the descriptions, just please go ahead and create the page and we can fill in the descriptions later?

Thanks,

John

**Comment by yanqingfu** [comment]
very nice videos, seems video 4 and video 5 are duplicate

**Comment by Saumya-Sunder** [comment]
Yeah, videos 4 and 5 are duplicate. Could we have someone delete one of the videos @johnbent ?

**Comment by Saumya-Sunder** [comment]
Done. Closing this as @novium258 confirmed that one of the duplicate videos have been deleted.
