### ISSUE TITLE
Red Hat CloudForms link in https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#434]
since we don't have instructions about red hat cloudforms

should we remove the link associated with red hat cloudforms ?

**Comment by justinzw** [comment]
Thanks for reporting this. We will look into this.

**Comment by mukul-seagate11** [comment]
@gauravchaudhari02, do we have update on this?

**Comment by gauravchaudhari02** [comment]
@Saumya-Sunder, Could you please resolve this?

**Comment by Saumya-Sunder** [comment]
Removed it here https://github.com/Seagate/cortx/pull/487

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, you can close the issue if its fixed from your end

**Comment by Saumya-Sunder** [comment]
Done [here](https://github.com/Seagate/cortx/pull/487) closing the issue.
