### ISSUE TITLE
Multi-node Configuration File

### ISSUE THREAD

**Issue by PengMacro** [Seagate/cortx#439]
I am trying to test multi-node and need to edit the configuration file.
https://github.com/Seagate/cortx/blob/main/doc/scaleout/Configuration_File.rst
How do I find my cluster_ip and mgmt_vip?

![image](https://user-images.githubusercontent.com/37490734/97285139-d8742b00-180f-11eb-83b5-9e7e7fa840bf.png)

**Comment by justinzw** [comment]
@ypise  would you know the answer to this question?

**Comment by ypise** [comment]
Greetings @PengMacro,
cluster_ip and mgmt_vip are expected to be provided by the Network Administrator managing your system environment.
These have to be static IPs and should not be assigned to any specific MAC on a DHCP server so that these could be assigned to any qualifying system in the multi-node node cluster.

If you have setup a private network, these values could be any IP addresses in same subnet as the other assigned IP on the same network interface.
They should be preferably within NetMask prefix 24 range.
Also. make sure these are not assigned to the nodes and are well beyond the possible IP ranges that these nodes could assume.

I hope that answers your question.

**Comment by PengMacro** [comment]
I created three networks containing four nodes (3 servers, 1 client). Below is the output of "ip a" from one server. Can I simply choose any of ip to be management, public data or private data ip? For instance, is the below config.ini working?


```
5: p2p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 3c:fd:fe:04:be:c2 brd ff:ff:ff:ff:ff:ff
    inet 10.10.2.1/24 brd 10.10.2.255 scope global p2p2
       valid_lft forever preferred_lft forever
    inet6 fe80::3efd:feff:fe04:bec2/64 scope link
       valid_lft forever preferred_lft forever
6: p1p1: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether a0:36:9f:85:7f:10 brd ff:ff:ff:ff:ff:ff
7: p1p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a0:36:9f:85:7f:11 brd ff:ff:ff:ff:ff:ff
    inet 10.10.1.1/24 brd 10.10.1.255 scope global p1p2
       valid_lft forever preferred_lft forever
    inet6 fe80::a236:9fff:fe85:7f11/64 scope link
       valid_lft forever preferred_lft forever
8: p1p3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a0:36:9f:85:7f:12 brd ff:ff:ff:ff:ff:ff
    inet 10.10.3.1/24 brd 10.10.3.255 scope global p1p3
       valid_lft forever preferred_lft forever
    inet6 fe80::a236:9fff:fe85:7f12/64 scope link
       valid_lft forever preferred_lft forever
```

```
[cluster]
cluster_ip=10.10.2.111
mgmt_vip=10.10.1.111

[storage_enclosure]
type=JBOD

[srvnode-1]
hostname=pc773.emulab.net
network.mgmt_nw.iface=p1p2
network.mgmt_nw.public_ip_addr=10.10.1.1
network.mgmt_nw.netmask=
network.mgmt_nw.gateway=
network.data_nw.iface=p2p2
network.data_nw.public_ip_addr=10.10.2.1
network.data_nw.netmask=
network.data_nw.gateway=
network.data_nw.pvt_ip_addr=10.10.3.1
is_primary=True
bmc.user=
bmc.secret=

[srvnode-2]
hostname=pc770.emulab.net
network.mgmt_nw.iface=p1p2
network.mgmt_nw.public_ip_addr=10.10.1.2
network.mgmt_nw.netmask=
network.mgmt_nw.gateway=
network.data_nw.iface=p2p2
network.data_nw.public_ip_addr=10.10.2.2
network.data_nw.netmask=
network.data_nw.gateway=
network.data_nw.pvt_ip_addr=10.10.3.2
is_primary=False
bmc.user=
bmc.secret=

[srvnode-3]
hostname=pc768.emulab.net
network.mgmt_nw.iface=p1p2
network.mgmt_nw.public_ip_addr=10.10.1.3
network.mgmt_nw.netmask=
network.mgmt_nw.gateway=
network.data_nw.iface=p2p2
network.data_nw.public_ip_addr=10.10.2.3
network.data_nw.netmask=
network.data_nw.gateway=
network.data_nw.pvt_ip_addr=10.10.3.3
is_primary=False
bmc.user=
bmc.secret=
```

**Comment by suntins** [comment]
> Thanks. @ypise
> 
> I created three networks containing four nodes (3 servers, 1 client). Below is the output of "ip a" from one server. Can I simply choose any of ip to be management, public data or private data ip? For instance, is the below config.ini working?
> 
> ```
> 5: p2p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether 3c:fd:fe:04:be:c2 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.2.1/24 brd 10.10.2.255 scope global p2p2
>        valid_lft forever preferred_lft forever
>     inet6 fe80::3efd:feff:fe04:bec2/64 scope link
>        valid_lft forever preferred_lft forever
> 6: p1p1: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
>     link/ether a0:36:9f:85:7f:10 brd ff:ff:ff:ff:ff:ff
> 7: p1p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether a0:36:9f:85:7f:11 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.1.1/24 brd 10.10.1.255 scope global p1p2
>        valid_lft forever preferred_lft forever
>     inet6 fe80::a236:9fff:fe85:7f11/64 scope link
>        valid_lft forever preferred_lft forever
> 8: p1p3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether a0:36:9f:85:7f:12 brd ff:ff:ff:ff:ff:ff
>     inet 10.10.3.1/24 brd 10.10.3.255 scope global p1p3
>        valid_lft forever preferred_lft forever
>     inet6 fe80::a236:9fff:fe85:7f12/64 scope link
>        valid_lft forever preferred_lft forever
> ```
> 
> ```
> [cluster]
> cluster_ip=10.10.2.111
> mgmt_vip=10.10.1.111
> 
> [storage_enclosure]
> type=JBOD
> 
> [srvnode-1]
> hostname=pc773.emulab.net
> network.mgmt_nw.iface=p1p2
> network.mgmt_nw.public_ip_addr=10.10.1.1
> network.mgmt_nw.netmask=
> network.mgmt_nw.gateway=
> network.data_nw.iface=p2p2
> network.data_nw.public_ip_addr=10.10.2.1
> network.data_nw.netmask=
> network.data_nw.gateway=
> network.data_nw.pvt_ip_addr=10.10.3.1
> is_primary=True
> bmc.user=
> bmc.secret=
> 
> [srvnode-2]
> hostname=pc770.emulab.net
> network.mgmt_nw.iface=p1p2
> network.mgmt_nw.public_ip_addr=10.10.1.2
> network.mgmt_nw.netmask=
> network.mgmt_nw.gateway=
> network.data_nw.iface=p2p2
> network.data_nw.public_ip_addr=10.10.2.2
> network.data_nw.netmask=
> network.data_nw.gateway=
> network.data_nw.pvt_ip_addr=10.10.3.2
> is_primary=False
> bmc.user=
> bmc.secret=
> 
> [srvnode-3]
> hostname=pc768.emulab.net
> network.mgmt_nw.iface=p1p2
> network.mgmt_nw.public_ip_addr=10.10.1.3
> network.mgmt_nw.netmask=
> network.mgmt_nw.gateway=
> network.data_nw.iface=p2p2
> network.data_nw.public_ip_addr=10.10.2.3
> network.data_nw.netmask=
> network.data_nw.gateway=
> network.data_nw.pvt_ip_addr=10.10.3.3
> is_primary=False
> bmc.user=
> bmc.secret=
> ```

@PengMacro Could you please show the output from command "ip r". Thanks

**Comment by PengMacro** [comment]
@suntins 
```
[root@node-0 home]# ip r
default via 155.98.36.1 dev em1
10.10.1.0/24 dev p1p2 proto kernel scope link src 10.10.1.1
10.10.2.0/24 dev p2p2 proto kernel scope link src 10.10.2.1
10.10.3.0/24 dev p1p3 proto kernel scope link src 10.10.3.1
155.98.36.0/22 dev em1 proto kernel scope link src 155.98.36.39

```

If you want to access those machines, please give the public key. Thanks!
(ssh pcpeng@pc739.emulab.net, pcpeng@pc721.emulab.net, pcpeng@pc722.emulab.net)

**Comment by ypise** [comment]
> Thanks. @ypise
> 
> 
> 
> I created three networks containing four nodes (3 servers, 1 client). Below is the output of "ip a" from one server. Can I simply choose any of ip to be management, public data or private data ip? For instance, is the below config.ini working?
> 
> 
> 
> 
> 
> ```
> 
> 5: p2p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
> 
>     link/ether 3c:fd:fe:04:be:c2 brd ff:ff:ff:ff:ff:ff
> 
>     inet 10.10.2.1/24 brd 10.10.2.255 scope global p2p2
> 
>        valid_lft forever preferred_lft forever
> 
>     inet6 fe80::3efd:feff:fe04:bec2/64 scope link
> 
>        valid_lft forever preferred_lft forever
> 
> 6: p1p1: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
> 
>     link/ether a0:36:9f:85:7f:10 brd ff:ff:ff:ff:ff:ff
> 
> 7: p1p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
> 
>     link/ether a0:36:9f:85:7f:11 brd ff:ff:ff:ff:ff:ff
> 
>     inet 10.10.1.1/24 brd 10.10.1.255 scope global p1p2
> 
>        valid_lft forever preferred_lft forever
> 
>     inet6 fe80::a236:9fff:fe85:7f11/64 scope link
> 
>        valid_lft forever preferred_lft forever
> 
> 8: p1p3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
> 
>     link/ether a0:36:9f:85:7f:12 brd ff:ff:ff:ff:ff:ff
> 
>     inet 10.10.3.1/24 brd 10.10.3.255 scope global p1p3
> 
>        valid_lft forever preferred_lft forever
> 
>     inet6 fe80::a236:9fff:fe85:7f12/64 scope link
> 
>        valid_lft forever preferred_lft forever
> 
> ```
> 
> 
> 
> ```
> 
> [cluster]
> 
> cluster_ip=10.10.2.111
> 
> mgmt_vip=10.10.1.111
> 
> 
> 
> [storage_enclosure]
> 
> type=JBOD
> 
> 
> 
> [srvnode-1]
> 
> hostname=pc739.emulab.net
> 
> network.mgmt_nw.iface=p1p2
> 
> network.mgmt_nw.public_ip_addr=10.10.1.1
> 
> network.mgmt_nw.netmask=
> 
> network.mgmt_nw.gateway=
> 
> network.data_nw.iface=p2p2
> 
> network.data_nw.public_ip_addr=10.10.2.1
> 
> network.data_nw.netmask=
> 
> network.data_nw.gateway=
> 
> network.data_nw.pvt_ip_addr=10.10.3.1
> 
> is_primary=True
> 
> bmc.user=
> 
> bmc.secret=
> 
> 
> 
> [srvnode-2]
> 
> hostname=pc721.emulab.net
> 
> network.mgmt_nw.iface=p1p2
> 
> network.mgmt_nw.public_ip_addr=10.10.1.2
> 
> network.mgmt_nw.netmask=
> 
> network.mgmt_nw.gateway=
> 
> network.data_nw.iface=p2p2
> 
> network.data_nw.public_ip_addr=10.10.2.2
> 
> network.data_nw.netmask=
> 
> network.data_nw.gateway=
> 
> network.data_nw.pvt_ip_addr=10.10.3.2
> 
> is_primary=False
> 
> bmc.user=
> 
> bmc.secret=
> 
> 
> 
> [srvnode-3]
> 
> hostname=pc722.emulab.net
> 
> network.mgmt_nw.iface=p1p2
> 
> network.mgmt_nw.public_ip_addr=10.10.1.3
> 
> network.mgmt_nw.netmask=
> 
> network.mgmt_nw.gateway=
> 
> network.data_nw.iface=p2p2
> 
> network.data_nw.public_ip_addr=10.10.2.3
> 
> network.data_nw.netmask=
> 
> network.data_nw.gateway=
> 
> network.data_nw.pvt_ip_addr=10.10.3.3
> 
> is_primary=False
> 
> bmc.user=
> 
> bmc.secret=
> 
> ```
> 
> 
> 
> 
> 
> 

@PengMacro 
The configuration that you have suggested looks good and should work.

In general, I would like to highlight that Management network is comparative a slower network to Data network.
Data network subnet needs to be high capacity high performance network for actual business data transfers. Whereas Management network is a control network for monitoring and correction services.

**Comment by PengMacro** [comment]
Moved to https://github.com/Seagate/cortx-prvsnr/issues/767
