### ISSUE TITLE
Better link to ICS

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#444]
For our monthly meetings (https://github.com/Seagate/cortx/blob/main/doc/meetings/README.rst), we have an ICS file which people should be able to click on and add to their calendars.  It works for phones and tablets but not for desktops/laptops.  Fix this link (or add more links) to make it a single click for people to add this to their calendars.

**Comment by johnbent** [comment]
https://office-watch.com/2017/web-links-adding-outlook-appointments-tricks-and-traps/  might be useful for Outlook events.

When it was still an open linkedin event, there was 3 links I think:
Add to Outlook
Add to Google Calendar
Download ICS

This link above might help for the first one.

https://stackoverflow.com/questions/35853870/href-to-add-to-calendar-from-web-not-working-with-native-google-calendar-app-o  also might be related.

**Comment by johnbent** [comment]
https://stackoverflow.com/questions/10488831/link-to-add-to-google-calendar also might be useful

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you document the same

**Comment by Saumya-Sunder** [comment]
It needs some digging as the links to add event on desktops is not working @mukul-seagate11 , I will close it once I have a proper working link.

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, do you have any timeline so that we can take this forward?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, please take care & close

**Comment by Saumya-Sunder** [comment]
@mukul-seagate11 I have let it remain open as I can create a calendar link for Gmail, iCalendar or mobile phones, however the link needs to be that for a single event and not a series of event. So this is an issue that I have no resolution for unless we decide to add links for events and update the event details on an ongoing basis.

**Comment by johnbent** [comment]
@Saumya-Sunder and @novium258 , here is a paid service that seems to have what we need: https://www.addevent.com/plans-and-pricing.  Should we try to get it?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, any further update or if done then this issue be closed?
