### ISSUE TITLE
Correct the Link pointed via _Server network striping_ in cortx/doc/be/sns-io-repair-rebalance.md

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx#447]
Needs fixing at line 5.

Make it point to a usable URL.

**Comment by Saumya-Sunder** [comment]
Thank you @raikrahul I am moving the file to a .md file! Appreciate your feedback :)

**Comment by Saumya-Sunder** [comment]
@huanghua78 I see a link to this [doc](https://seagatetechnology-my.sharepoint.com/:w:/g/personal/hua_huang_seagate_com/Eb0CTiI3VbdAhLzn8NufzisBj_OFeA4bnKw3Pu0X0jJGVA?e=4%3A8psKWK&at=9&CID=c7fca889-7248-8d1b-0701-0641fb87566d) that I need to convert into a .md file. Also there is another link in the doc [here](https://docs.google.com/a/xyratex.com/Doc?docid=0ATg1HFjUZcaZZGNkNXg4cXpfMTc5ZjYybjg4Y3Q&hl=en) that says it that the doc has been deleted. Could you help me understand what this info is?

**Comment by johnbent** [comment]
Hey @Saumya-Sunder , has this been fixed yet?

**Comment by Saumya-Sunder** [comment]
Hey @johnbent , its done here https://github.com/Seagate/cortx/pull/491. I have shared the issue I am facing with Plant UML diagram alignment here: https://liveuml.com/view/5fc5fdf04796fa7b0d135704

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you please update if its fixed?

**Comment by Saumya-Sunder** [comment]
Done [here](https://github.com/Seagate/cortx/pull/491) closing the issue.
