### ISSUE TITLE
Fix the links in /doc/be/sns-io-repair-rebalance.md#references

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx#448]
https://github.com/Seagate/cortx/blob/main/doc/be/sns-io-repair-rebalance.md#references

None of the links mentioned open up.

**Comment by johnbent** [comment]
Thanks for reporting this @raikrahul !

**Comment by Saumya-Sunder** [comment]
Done https://github.com/Seagate/cortx/pull/491
