### ISSUE TITLE
Correct the JIRA link at main/doc/be/authserver_notes.rst#ceph-cortx-s3-failures

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx#449]
https://github.com/Seagate/cortx/blob/main/doc/be/authserver_notes.rst#ceph-cortx-s3-failures

Must not point to an accessible page

**Comment by Saumya-Sunder** [comment]
@raikrahul it's fixed here https://github.com/Seagate/cortx/blob/main/doc/be/authserver_notes.rst#ceph-cortx-s3-failures
