### ISSUE TITLE
readme.md link to youtube is broken

### ISSUE THREAD

**Issue by kaplanlior** [Seagate/cortx#459]
Refers to https://cortx.link/XGVHVq which doesn't work.

Should refer to https://www.youtube.com/playlist?list=PLOLUar3XSz2M_w5OxQLNDBTpSrsGbjDWr

**Comment by justinzw** [comment]
Thanks @kaplanlior for fixing this.

@novium258 could you fix that on your end?

@kaplanlior I love the feedback on the documentation. If you see anything that needs improvements don't hesitate to let us know. + @johnbent as an FYI.

**Comment by johnbent** [comment]
Thanks!  @Saumya-Sunder fixed this!
