### ISSUE TITLE
Document error in "CORTX v1.0 Virtual Clusters Setup"

### ISSUE THREAD

**Issue by PengMacro** [Seagate/cortx#469]
![image](https://user-images.githubusercontent.com/37490734/99062259-56eaff80-2568-11eb-86c6-4da76b42c4dc.png)

I think this should be 0x20 (same for the below mocat command).

**Comment by mukul-seagate11** [comment]
@VenkyOS, please check with component team & update the doc

**Comment by VenkyOS** [comment]
@PengMacro - Can you please provide the link to the concerned document.

**Comment by PengMacro** [comment]
https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md

**Comment by VenkyOS** [comment]
@mukul-seagate11 and @justinzw - Can we assign this to somebody from the Motr team to get more clarity?

**Comment by VenkyOS** [comment]
The below mentioned PR addresses the issue.

[Issue](https://github.com/Seagate/cortx/pull/489)
