### ISSUE TITLE
Duplicate codeowners file

### ISSUE THREAD

**Issue by gauravchaudhari02** [Seagate/cortx#480]
@johnbent seems like we have two `CODEOWNERS` file present in cortx repository as follow,

https://github.com/Seagate/cortx/blob/main/CODEOWNERS
https://github.com/Seagate/cortx/blob/main/.github/CODEOWNERS

We could remove one sitting at the root of the repository

**Comment by shailesh-vaidya** [comment]
@gauravchaudhari02  Seems GitHub supports CODEOWNERS file from both root and .github folder. https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-file-location 
However for clean way we should remove https://github.com/Seagate/cortx/blob/main/CODEOWNERS

**Comment by gauravchaudhari02** [comment]
> @gauravchaudhari02 Seems GitHub supports CODEOWNERS file from both root and .github folder. https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-file-location
> However for clean way we should remove https://github.com/Seagate/cortx/blob/main/CODEOWNERS

Agree with you @shailesh-vaidya. 👍🏼

**Comment by johnbent** [comment]
Agree it is cleaner as @shailesh-vaidya says.  :)

**Comment by johnbent** [comment]
Fixed: https://github.com/Seagate/cortx/commit/2371b60a462ea3f68c27657bdb7304394ace6839
