### ISSUE TITLE
Show people how to watch Discussions only

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#482]
For community members who want to 'subscribe' to the CORTX mailing list, github Discussions is the best way to do this.  @Saumya-Sunder , can you add a screenshot to SUPPORT.md and document how to do this?

![image](https://user-images.githubusercontent.com/2047294/99997107-ec14a200-2d79-11eb-9543-872eb51ca251.png)

![image](https://user-images.githubusercontent.com/2047294/99997133-f46cdd00-2d79-11eb-95fa-7e832a606bf5.png)

**Comment by Saumya-Sunder** [comment]
Sure @johnbent. I will add the steps right after the link on discussions link. Would that be ok?

**Comment by johnbent** [comment]
Exactly.  As a sub-bullet or something.
________________________________

**Comment by justinzw** [comment]
this is awesome, thanks for finding this @johnbent

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you please document the same as suggested
