### ISSUE TITLE
Clovis string is showing in CORE Architecture document.

### ISSUE THREAD

**Issue by imvenkip** [Seagate/cortx#485]
Clovis string is showing in CORTX CORE Arch document.
Mero string is showing in Images. 
I believe, we have to replace clovis with Motr.
         https://github.com/Seagate/cortx/blob/main/doc/be/CORTX_CORE_ARCHITECTURE.rst

**Comment by huanghua78** [comment]
This is fixed by https://github.com/Seagate/cortx/pull/486
