### ISSUE TITLE
yum repos need to be hosted outside of Seagate network

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx#493]
**Repro steps:**

Following these instructions: https://github.com/Seagate/Cortx/blob/main/doc/Cluster_Setup.md

This step fails `sudo yum install -y cortx-hare`

with this error: `http://cortx-storage.colo.seagate.com/releases/cortx/github/release/rhel-7.7.1908/last_successful/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: cortx-storage.colo.seagate.com; Unknown error"
Trying other mirror.`

**Issue:**

We should host the yum repo outside the Seagate network.

**Comment by justinzw** [comment]
@mukul-seagate11 @shailesh-vaidya 

Would one of you be able to the repo to github for us?

**Comment by shailesh-vaidya** [comment]
@justinzw  -  https://github.com/Seagate/Cortx/blob/main/doc/Cluster_Setup.md is referencing to Seagate internal repository link at https://github.com/Seagate/Cortx/blob/main/doc/Cluster_Setup.md#12-install-the-rpms  . Need to fix this. 

Currently we are only releasing [OVA](https://github.com/Seagate/cortx/releases/tag/VA) and [JBOD](https://github.com/Seagate/cortx/releases/tag/JBOD) artifacts. `cortx-hare` package is generated from https://github.com/Seagate/cortx-hare repository.  In this document we should update instructions to generate cortx-hare package and use it.  Similar issues was discussed in https://github.com/Seagate/cortx/issues/296

**Comment by Saumya-Sunder** [comment]
@shailesh-vaidya should I document the steps?

**Comment by mukul-seagate11** [comment]
@shailesh-vaidya, cam you please update?

**Comment by shailesh-vaidya** [comment]
Hi @Saumya-Sunder  - Yes. We need to update steps at https://github.com/Seagate/Cortx/blob/main/doc/Cluster_Setup.md#12-install-the-rpms 
For all CORTX packages to use please add steps to build required packages or add link to component repository wiki links.

**Comment by mssawant** [comment]
@Saumya-Sunder please find the steps for hare installation from sources at https://github.com/Seagate/cortx-hare/pull/1431/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by Saumya-Sunder** [comment]
Thanks @mssawant! Updated the guide in PR https://github.com/Seagate/cortx/pull/518 and closing the issue as it is addressed.
