### ISSUE TITLE
Create pages about hackathons

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#516]
1. Create a top-level page about hackathons in general
2. Link that from existing documentation
3. Create a child page about our first hackathon
    a. Use materials from https://drive.google.com/file/d/1OmWVKhKLBqmM9rn14iw2vBn0mOscuf1S/view
    b. Use materials from https://seagatetechnology.sharepoint.com/:f:/r/sites/CORTX/Shared%20Documents/Open%20Source?csf=1&web=1&e=bRW2YK

**Comment by mukul-seagate11** [comment]
@VenkyOS, please document the same as suggested

**Comment by VenkyOS** [comment]
@johnbent , @mukul-seagate11 - I have created the document as required. Please find below the PR link.

[Hackathon_Document](https://github.com/Seagate/cortx/pull/524)

**Comment by VenkyOS** [comment]
Closing this issue as this has been addressed.

https://github.com/Seagate/cortx/blob/main/doc/CORTX_Hackathon.rst
