### ISSUE TITLE
Add list of suggested integrations to integration page

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#522]
@Saumya-Sunder , can you please add a list of suggested integrations at the bottom of our integrations page?  With links.
HDF5 -> https://www.hdfgroup.org/downloads/hdf5/source-code/
And also pull the ones from the spreadsheet I just shared with you please that aren't yet crossed out.  Then replace all the text on that tab in that spreadsheet please with something that says, "Moved to our github integrations page (link)".  Thanks!

**Comment by Saumya-Sunder** [comment]
Sure @johnbent

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can you take this forward?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, please take this forward?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, any further update on this?

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, do you have any update on this issue?

**Comment by mukul-seagate11** [comment]
As I see no update on the issue so closing accordingly
