### ISSUE TITLE
Add a bot to acknowledge contributors across all our repos

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#525]
https://allcontributors.org/docs/en/bot/overview

**Comment by johnbent** [comment]
This can also give us a badge that shows our contributors count:
![image](https://user-images.githubusercontent.com/2047294/102681704-f3647b00-4180-11eb-90ce-71f85b417934.png)

https://raw.githubusercontent.com/all-contributors/all-contributors/master/README.md

**Comment by mukul-seagate11** [comment]
@pujamudaliar, can we take this forward for all repos as suggested?

**Comment by mukul-seagate11** [comment]
@pujamudaliar, please take this forward for all repos to get added

**Comment by mukul-seagate11** [comment]
@johnbent, contributor badges with count has been added for the repos as per,

![image](https://user-images.githubusercontent.com/65269273/111109264-6d3db200-8580-11eb-800b-f339226e5731.png)

https://github.com/Seagate/cortx/pull/828
https://github.com/Seagate/cortx-motr/pull/496
https://github.com/Seagate/cortx-prvsnr/pull/1002
https://github.com/Seagate/cortx-utils/pull/231
https://github.com/Seagate/cortx-monitor/pull/341
https://github.com/Seagate/cortx-s3server/pull/760
https://github.com/Seagate/cortx-hare/pull/1541
https://github.com/Seagate/cortx-ha/pull/342
https://github.com/Seagate/cortx-experiments/pull/69/ -> Closed as not required
https://github.com/Seagate/cortx-management-portal/pull/304
https://github.com/Seagate/cortx-manager/pull/411
https://github.com/Seagate/cortx-posix/pull/310 -> Closed as not required
