### ISSUE TITLE
How to Debug CORTX Guide Needed

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#533]
@VenkyOS , please ask @just-now , @andriytk , and @huanghua78 whether there is any existing documentation about how to debug CORTX.  Please take whatever documents are found and consolidate them into a single guide and add that guide to this repo and link it accordingly.  Thanks!

**Comment by VenkyOS** [comment]
@johnbent - Sure. I will proceed accordingly.

**Comment by mukul-seagate11** [comment]
@VenkyOS, Kindly take care & close

**Comment by VenkyOS** [comment]
@mukul-seagate11 - I have started working on this. In this regard, spoke to the relevant stakeholders.

**Comment by johnbent** [comment]
@VenkyOS apparently there is a tool called m0reportbug which sounds like it should be included in this guide.

**Comment by mukul-seagate11** [comment]
@VenkyOS, Can you evaluate m0reportbug as suggested & include the same in the doc

**Comment by VenkyOS** [comment]
@johnbent and @mukul-seagate11 - I have spoken to @just-now about this. He would revert post the end of this week.
