### ISSUE TITLE
Running Cortx on Oracle VM VirtualBox

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx#539]
Regarding to the Documentation [Cortx on OVA](https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst)
It seems that the released OVA file can run just fine on Oracle VM VirtualBox, I am wondering if there's any reason that no instructions are given for setup on Oracle VM VirtualBox?

Also, correct me if I'm wrong, running VMWare Workstation requires license fee and I think Oracle VM would be a great alternative?

_*Tested on Windows 10 Desktop._

**Comment by mukul-seagate11** [comment]
@VenkyOS, Can you check & verify from Oracle VirtualBox?

@harrison-seow-seagate, 

>Also, correct me if I'm wrong, running VMWare Workstation requires license fee and I think Oracle VM would be a great alternative?
You dont require VMware Workstation license as such for testing, you can even test with the trial version as well and would suggest to use the same

**Comment by VenkyOS** [comment]
@mukul-seagate11 - I will look into this.

@harrison-seow-seagate - You are correct. Workstation does not require license for testing. OVA can be tested on WorkStation using the trial version. Information about Oracle VirtualBox was not documented initially. I will talk to the team and get the document updated.

Thanks

**Comment by harrison-seow-seagate** [comment]
Although I was able to get it running on Oracle VM VirtualBox, I had to boot the rescue OS and rename Network Devices, but other than that, S3 seems to work just fine from the testing.

**Comment by johnbent** [comment]
@harrison-seow-seagate , submitting a PR to add the missing documentation for Oracle VM VirtualBox would be a great contribution!  👍

**Comment by VenkyOS** [comment]
@johnbent - Can this issue be closed?

**Comment by johnbent** [comment]
Sure.  It can be closed.  Thanks.
________________________________

**Comment by VenkyOS** [comment]
A PR has been raised in this regard.
