### ISSUE TITLE
install dependencies on physical server fails per guide

### ISSUE THREAD

**Issue by korenlev** [Seagate/cortx#540]
following this : https://github.com/Seagate/cortx/blob/main/doc/InstallingDependencies.md by https://github.com/Saumya-Sunder  , not sure what step 1. means, but did all step 2 on centos server and step 3 yields errror :

[root@rack-a-node-1 cortx-build-dependencies]# yum list cortx-py-utils
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.spd.co.il
 * extras: centos.spd.co.il
 * updates: centos.spd.co.il
Error: No matching Packages to list
[root@rack-a-node-1 cortx-build-dependencies]# ls
bazel-0.13.0-1.el7.x86_64.rpm             ossperf-3.0-1.x86_64.rpm
compat-lua-libs-5.1.5-3.el7.x86_64.rpm    python2-botocore-1.6.0-1.el7.noarch.rpm
consul-1.7.8-1.x86_64.rpm                 python2-jmespath-0.9.0-1.el7.noarch.rpm
git-clang-format-6.0-1.el7.x86_64.rpm     python2-s3transfer-0.1.10-1.el7.noarch.rpm
gtest-1.10.0-1.el7.x86_64.rpm             python36-boto3-1.4.6-1.el7.noarch.rpm
gtest-devel-1.10.0-1.el7.x86_64.rpm       python36-botocore-1.6.0-1.el7.noarch.rpm
haproxy-1.8.14-1.el7.x86_64.rpm           python36-cortx-prvsnr-0.36.0-1.0.0.x86_64.rpm
haproxy-statsd-1.0-1.x86_64.rpm           python36-jmespath-0.9.0-1.el7.noarch.rpm
libevhtp-1.2.18-2.el7.x86_64.rpm          python36-s3transfer-0.1.10-1.el7.noarch.rpm
libevhtp-devel-1.2.18-2.el7.x86_64.rpm    python36-wheel-0.24.0-2.el7.noarch.rpm
libntirpc-1.8.1-0.1.el7.x86_64.rpm        python36-xmltodict-0.9.0-1.el7.noarch.rpm
libntirpc-devel-1.8.1-0.1.el7.x86_64.rpm  python-jmespath-0.9.0-1.el7.noarch.rpm
log4cxx_cortx-0.10.0-1.x86_64.rpm         python-wheel-0.24.0-2.el7.noarch.rpm
log4cxx_cortx-devel-0.10.0-1.x86_64.rpm   repodata
lua-5.3.0-2.el7.x86_64.rpm                s3cmd-1.6.1-1.el7.noarch.rpm
nfs-ganesha-2.8.4-0.1.el7.x86_64.rpm      systemd-python36-1.0.0-523_git7908548.el7.x86_64.rpm
nfs-ganesha-vfs-2.8.4-0.1.el7.x86_64.rpm  systemd-python36-debuginfo-1.0.0-523_git7908548.el7.x86_64.rpm

+ what are the install steps after dep repo , because some dep have dep on missing pkgs , example 👍 
[root@rack-a-node-1 cortx-build-dependencies]# yum install ossperf
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.spd.co.il
 * extras: centos.spd.co.il
 * updates: centos.spd.co.il
Resolving Dependencies
--> Running transaction check
---> Package ossperf.x86_64 0:3.0-1 will be installed
--> Processing Dependency: s3cmd >= 1.6.1 for package: ossperf-3.0-1.x86_64
--> Processing Dependency: parallel for package: ossperf-3.0-1.x86_64
--> Running transaction check
---> Package ossperf.x86_64 0:3.0-1 will be installed
--> Processing Dependency: parallel for package: ossperf-3.0-1.x86_64
---> Package s3cmd.noarch 0:1.6.1-1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: ossperf-3.0-1.x86_64 (root_cortx-build-dependencies)
           Requires: parallel
 You could try using --skip-broken to work around the problem
^C[root@rack-a-node-1 cortx-build-dependencies]# yum install parallel
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.spd.co.il
 * extras: centos.spd.co.il
 * updates: centos.spd.co.il
No package parallel available.
Error: Nothing to do

**Comment by korenlev** [comment]
+ what are the install steps coming next for all dependencies

**Comment by johnbent** [comment]
@daniarherikurniawan, did you get it working on bare metal?
@suntins, did you?
This document shows bare-metal install (but on a cluster of 3):[LINK](https://github.com/Seagate/cortx/blob/main/doc/scaleout/README.rst )
This document also might be useful: [LINK](https://github.com/Seagate/Cortx/blob/main/doc/Cluster_Setup.md)

**Comment by korenlev** [comment]
Links not helpful , i need install guide on single server please

בתאריך יום ג׳, 5 בינו׳ 2021, 18:37, מאת John Bent ‏<notifications@github.com

**Comment by johnbent** [comment]
Thanks @korenlev , unfortunately, I don't think that exists.  If you can get it working from these docs, then it would be awesome if you could help document what you did for the next person who wants to do this.

**Comment by huanghua78** [comment]
@korenlev What CORTX components are you trying to install and configure?

If you are trying to use CORTX-Motr, I don't think these dependencies are needed.

**Comment by huanghua78** [comment]
@johnbent @Saumya-Sunder we need to understand what components need this dependency list.
If they are needed by some specific component, we need to move this document to that specific component.
Otherwise, people will get confused. They will think this is the first step to try before trying CORTX-Motr, CORTX-Hare, etc. It seems @shailesh-vaidya prepared the original document. Maybe @shailesh-vaidya can explain.

**Comment by korenlev** [comment]
I am trying to install all cortx , just like available in the OVA (VM),
someone built it right? He can help...

בתאריך יום ד׳, 6 בינו׳ 2021, 10:58, מאת Huang Hua ‏<notifications@github.com

**Comment by shailesh-vaidya** [comment]
@huanghua78  - Other that CORTX-Motr and CORTX-Hare most of the component needs third party packages for build. Hence instead of Developer to search and download them individually we have added them in single location. This just to simplify the build process. 

@korenlev  cortx-py-utils is not third party package but build from [cortx-utils](https://github.com/Seagate/cortx-utils) repo . Instructions to build it is available at https://github.com/Seagate/cortx-utils/tree/main/py-utils 

@Saumya-Sunder  - We should correct https://github.com/Seagate/cortx/blob/main/doc/InstallingDependencies.md . Use some other package than `cortx-py-utils` to validate that repo is created properly.

For 
```
Error: Package: ossperf-3.0-1.x86_64 (root_cortx-build-dependencies)
Requires: parallel
You could try using --skip-broken to work around the problem
```
Few dependencies like `parallel` are installed from epel repo. Component document should have steps to enable epel repo else we can add it here. 
We can enable epel repo using ` yum install epel-release -y` . This will enable epel repo and install all dependencies. 

I can help you in building all CORTX components. We are trying to address all such dependency issues using CORTX build Docker image. Currently its in testing phase.

**Comment by korenlev** [comment]
Guys, it will be great to get early look into docker build when u have it,
even test phase, hoping it will have all cortx components,  this can make
the install amazingly easy.

For now, please, if a developer that have a simple cheetsheet (just the
commands and repos erc) for install on vanilla centos it will be awsome and
help us build the intergration lab !

בתאריך יום ד׳, 6 בינו׳ 2021, 14:11, מאת Shailesh Vadiya ‏<
notifications@github.com>:

**Comment by korenlev** [comment]
Guys, it will be great to get early look into docker build when u have it,
> even test phase, hoping it will have all cortx components,  this can make
> the install amazingly easy.
>

Shailesh Vadiya‬‏ , maybe next week we can get on webex and give u access
to my server ?

**Comment by shailesh-vaidya** [comment]
> Guys, it will be great to get early look into docker build when u have it,
> even test phase, hoping it will have all cortx components, this can make the install amazingly easy.
> Shailesh Vadiya‬‏ , maybe next week we can get on webex and give u access to my server ?

@korenlev  - Sure. Let me know your suitable time and we can sync-up over webex.

**Comment by johnbent** [comment]
@shailesh-vaidya and @korenlev , please do record this meeting and share it out with the rest of us afterwards.  I definitely want to make sure that everything learned is appropriately documented in github.  Koren, you are pushing us to do some very important things so thank you very much!

**Comment by korenlev** [comment]
Thanks john, I will record and document it all on sharepoint so everyone
can look and decide what/how to push forward..

Br
Koren


בתאריך יום ד׳, 6 בינו׳ 2021, 23:04, מאת John Bent ‏<notifications@github.com

**Comment by mukul-seagate11** [comment]
@korenlev, I see that you will be recording and documenting all on sharepoint so can we close the issue as we good?

**Comment by Saumya-Sunder** [comment]
@mukul-seagate11 I have a meeting with  @korenlev on Tuesday to document this properly, I will keep you updated.

**Comment by shailesh-vaidya** [comment]
@korenlev  We have published docker image to build entire CORTX at https://github.com/orgs/Seagate/packages/container/package/cortx-build as mentioned in https://github.com/Seagate/cortx/issues/540#issuecomment-755264463

Instructions to build CORTX packages using this Docker image is documented at - https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst

You can try that out and let us know if any issues or modifications required.

**Comment by shailesh-vaidya** [comment]
@korenlev  Could you please let use know if you are able to build component packages using https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst

**Comment by korenlev** [comment]
iso creation fine
note: iso boot fails on bare metal server (not VM)
but howto install on bare metal server starting from centOS stage (vanilla centos) running on the server ?

**Comment by shailesh-vaidya** [comment]
Hi @korenlev  This ISO is not bootable ISO. It's just collection of CORTX and Required Third Party rpm's packaged together. 
You can use following guides to Deploy CORTX - 
https://github.com/Seagate/cortx-prvsnr/wiki/Auto-Deploy-VM-Provisioner-CLI-Commands

**Comment by korenlev** [comment]
yes, deploy on VM , i know this.

sorry, i am looking for install guide for a 'regular' server , starting from centos vanilla and all the way to complete cortx running on that server

**Comment by johnbent** [comment]
FYI @hessio is also working on this same thing and trying to make sure we have everything nicely documented starting at root document https://github.com/Seagate/cortx/blob/main/QUICK_START.md.

**Comment by mukul-seagate11** [comment]
@hessio , did you get a chance to test & update?

**Comment by hessio** [comment]
I am still trying to have a guide that works for running this iso @mukul-seagate11

**Comment by mukul-seagate11** [comment]
@bariarviv, have you come across similar issue as according to @justinzw its install successfully on physical server?

**Comment by mukul-seagate11** [comment]
@all, can we have update on this?

**Comment by mukul-seagate11** [comment]
As there was no update so please feel free to reopen the issue if this issue is being encountered again.
