### ISSUE TITLE
Docker image for CORTX

### ISSUE THREAD

**Issue by kiwionly** [Seagate/cortx#544]
Hi, 

I just wondering is that a good idea to have a docker image for CORTX ? it might be more easy to for running as a Demo.

I had successfully running CORTX using vmware workstation follow this [instruction](https://github.com/Seagate/cortx/blob/e5bce45305a65cce7f9be553ecef8a44b9c3b2e4/doc/CORTX_on_Open_Virtual_Appliance.rst), but still is not so simple as every version of the vmware might have difference kind of issue.

Using docker might be more easier ?

**Comment by mukul-seagate11** [comment]
@kiwionly, yes that's a good idea which is actually in our roadmap but currently we had tested on virtual machine's

**Comment by kiwionly** [comment]
noted.
