### ISSUE TITLE
Link for "GitHub Tools and Procedures" no longer work

### ISSUE THREAD

**Issue by kiwionly** [Seagate/cortx#545]
Hi, 

I just found out the link under the page **[Contribute to the CORTX Project](https://github.com/Seagate/cortx/blob/e5bce45305a65cce7f9be553ecef8a44b9c3b2e4/CONTRIBUTING.md)** under section **Contribution Process** the link for **GitHub Tools and Procedures** had no longer work.

Try search the page for faster locate the hyperlink,

**Comment by mukul-seagate11** [comment]
@kiwionly, the doc has been moved to https://github.com/Seagate/cortx/blob/main/doc/GitHub_Processes_and_Tools.rst

**Comment by johnbent** [comment]
Thank you very much for reporting this @kiwionly !  I have submitted a PR to fix this so now (thanks to you!) the next person attempting this will have a better experience.  :)

**Comment by johnbent** [comment]
https://github.com/Seagate/cortx/pull/547
