### ISSUE TITLE
Broken link on "Working with Git for CORTX"

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx#551]
Hi, 

I just encounter a broken link from page "Working with Git for CORTX" when browse through document.

Path = **cortx/doc/working_with_git.md**
location = 
1. Prerequisities
...
Generate SSH and **PAT** access for your GitHub Account.

The **PAT** link no longer work.

**Comment by VenkyOS** [comment]
The below mentioned PR will resolve this issue.

https://github.com/Seagate/cortx/pull/553
