### ISSUE TITLE
Broken Link on /doc/architecture.md

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx#557]
Hi, 

I had encounter a broken link.

Path = /doc/architecture.md
link = CORTX Core Architecture Overview (/doc/CORTX_MOTR_ARCHITECTURE.rst)

This link have move to **seagate/cortx-motr/doc/CORTX_MOTR_ARCHITECTURE.rst**

Regards.

**Comment by mukul-seagate11** [comment]
@VenkyOS, please fix the broken link

**Comment by VenkyOS** [comment]
This issue is fixed with the below mentioned PR.

[PR](https://github.com/Seagate/cortx/pull/558)
