### ISSUE TITLE
Add a youtube banner

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#564]
We should add a channel to your youtube channel with our other banners:

![image](https://user-images.githubusercontent.com/2047294/104516895-5a275980-55b2-11eb-953e-ac798fd72ee8.png)

@TechWriter-Mayur, can you handle this please?

**Comment by johnbent** [comment]
Thanks @TechWriter-Mayur !

**Comment by TechWriter-Mayur** [comment]
Fixed in PR #566.

**Comment by TechWriter-Mayur** [comment]
Fixed in PR #566.

**Comment by johnbent** [comment]
Hey @TechWriter-Mayur , actually this looks great but you didn't use our vanity URL.  Can you please change the link to use: https://cortx.link/videos?

**Comment by TechWriter-Mayur** [comment]
Just updated the vanity URL and created the PR #577
