### ISSUE TITLE
Need more getting started guides

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#598]
We need the following getting started guides and the following bullet lists in our parent README:

- Download a CORTX VM image for easy testing
    - Run it on a single node [LINK](https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst)]
    - Run it on a cluster [NOT DONE]
- Download CORTX as prepackaged software releases
    - Run it on a single node [NOT DONE]
    - Run it across a cluster [DONE?](https://github.com/Seagate/cortx/blob/main/doc/scaleout/README.rst)
- Build motr from the source [DONE](https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst)
    - Run freshly built motr on a single node [DONE](https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst)
    - Run freshly built motr on a cluster [NOT DONE]
- Build motr + S3 from the source [DONE?](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md)
    - Run freshly built motr + S3  on a single node [DONE?](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md)
    - Run freshly built motr + S3 on a cluster [NOT DONE]
- Build entire CORTX from the source [DONE?](https://github.com/Seagate/cortx-hare/blob/main/README.md)
    - Run it on a single node [NOT DONE]
    - Run it on a cluster [NOT DONE]

**Comment by johnbent** [comment]
These bullets should go in both our parent README and our parent QSG.

**Comment by mukul-seagate11** [comment]
@VenkyOS, do take care in your new PR as suggested

**Comment by VenkyOS** [comment]
> @VenkyOS, do take care in your new PR as suggested

@mukul-seagate11 - Sure. I will look into this.
