### ISSUE TITLE
Install More Bots

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#629]
For all of our public repos, we should install the following bots:

- [ ] https://probot.github.io/apps/markdownify/
- [ ] https://probot.github.io/apps/all-contributors/
- [ ] https://github.com/behaviorbot/first-pr-merge
- [ ] https://github.com/behaviorbot/new-pr-welcome
- [ ] https://github.com/behaviorbot/sentiment-bot
- [ ] https://github.com/behaviorbot/welcome

**Comment by mukul-seagate11** [comment]
![image](https://user-images.githubusercontent.com/65269273/106093297-02622400-6156-11eb-83e9-337c6da3c1d0.png)

**Comment by mukul-seagate11** [comment]
![Uploading image.png…]()

**Comment by mukul-seagate11** [comment]
Bots are installed as per EOS-17051

**Comment by mukul-seagate11** [comment]
sentiment bot has been included in cortx/config.yml,

![image](https://user-images.githubusercontent.com/65269273/106412912-cb01b900-646e-11eb-9f39-8e42ae69244a.png)

**Comment by johnbent** [comment]
Awesome.  Thanks @mukul-seagate11 .  Is sentiment-bot install for just the parent repo or for all repos?  Did we ever test it?

**Comment by mukul-seagate11** [comment]
> Awesome. Thanks @mukul-seagate11 . Is sentiment-bot install for just the parent repo or for all repos? Did we ever test it?

sentiment bot is installed for only parent repo right now and tested but seems not being populated based on sentiment word/phrase
