### ISSUE TITLE
Triage bot is failing?

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#630]
After creating a new Issue (https://github.com/Seagate/cortx/issues/629), I got an email that triage failed with a link to this:https://github.com/Seagate/cortx/actions/runs/515516207
![image](https://user-images.githubusercontent.com/2047294/106016203-729c7700-607c-11eb-94a6-f53119288abb.png)
Looks like a problem with our triage bot?

**Comment by mukul-seagate11** [comment]
@johnbent, I had removed the triage workflow from cortx repo,

![image](https://user-images.githubusercontent.com/65269273/106088200-82cf5780-614b-11eb-8615-daa894049737.png)

![image](https://user-images.githubusercontent.com/65269273/106088242-97135480-614b-11eb-8931-4b8a0e157023.png)
