### ISSUE TITLE
SSO connection reset

### ISSUE THREAD

**Issue by nikitadanilov** [Seagate/cortx#65]
Few times a day, when trying to access github.com/Seagate, I am getting 
![Screen Shot 2020-07-09 at 20 36 57](https://user-images.githubusercontent.com/357282/87652291-afe28c80-c75c-11ea-8240-8434a91242e7.png)
Following the link gets me to
![Screen Shot 2020-07-09 at 20 37 06](https://user-images.githubusercontent.com/357282/87652346-c557b680-c75c-11ea-942d-09a6c044e5bb.png)
which after some time results in
![Screen Shot 2020-07-09 at 20 38 26](https://user-images.githubusercontent.com/357282/87652374-ce488800-c75c-11ea-9188-c5acc8579564.png)
The only known way to fix this is by following a little dance of clearing all browser cookies for ssologin.seagate.com.

I have Seagate VPN active, all other services work fine.

**Comment by justinzw** [comment]
Now that we are open source if we remove you from the Seagate org then you won't need SSO anymore. FWIW I also see this issue

**Comment by vvv** [comment]
> \[...\] if we remove you from the Seagate org then you won't need SSO anymore.

@justinzw What are the side effects of being removed from Seagate GitHub org?
