### ISSUE TITLE
Doc to convert

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#684]
You might be interested in http://gerrit.mero.colo.seagate.com/plugins/gitiles/mero/+/refs/heads/dev/layout-plan/layout/plan.h that defines never implemented 'layout plan' interface that would allow a generic and fault-tolerant implementation of function shipping.

@TechWriter-Mayur , can you convert this please and put somewhere appropriately into cortx-motr repo. And link to an existing document as always please.

**Comment by TechWriter-Mayur** [comment]
> 
> 
> You might be interested in http://gerrit.mero.colo.seagate.com/plugins/gitiles/mero/+/refs/heads/dev/layout-plan/layout/plan.h that defines never implemented 'layout plan' interface that would allow a generic and fault-tolerant implementation of function shipping.
> 
> @TechWriter-Mayur , can you convert this please and put somewhere appropriately into cortx-motr repo. And link to an existing document as always please.

Hi John. The plan.h file is already available in the GitHub. Please follow below link to view the document: [Layout.h](https://github.com/Seagate/cortx-motr/blob/main/layout/layout.h)

**Comment by johnbent** [comment]
Thanks @TechWriter-Mayur !
