### ISSUE TITLE
Add links to FAQS under the history section

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#703]
https://arxiv.org/pdf/1807.03632.pdf
http://www.pdsw.org/pdsw-discs16/wips/danilov-wip-pdsw-discs16.pdf
https://www.hpcwire.com/2016/11/29/seagate-led-sage-project-delivers-update-exascale/
https://sagestorage.eu/sites/default/files/Sage%20White%20Paper%20v1.0.pdf

@sainarasim @gregnsk any other good papers from the historical period?

**Comment by johnbent** [comment]
@Saumya-Sunder , can you take this one please?

**Comment by Saumya-Sunder** [comment]
Sure @johnbent

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, any update on this

**Comment by mukul-seagate11** [comment]
@Saumya-Sunder, can this issue be closed?

**Comment by mukul-seagate11** [comment]
closing the issue as no update is received

**Comment by mukul-seagate11** [comment]
@novium258, can you look into the issue or close if not required

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~535110] [~930816] 
I see Sage listed in here, where does this 'live'  I don't recognize anything CORTX Dev about these docs?
