### ISSUE TITLE
Missing a reference to OVF file creation using OVA

### ISSUE THREAD

**Issue by gregnsk** [Seagate/cortx#704]
From the https://github.com/Seagate/cortx/blob/main/doc/Importing_OVA_File.rst:
_If you are facing errors due to usage of old versions, perform the below mentioned procedure.
Right-click the .ovf file and edit it in a text editor (preferably, notepad)._

We release CORTX VM as the OVA. Please add a reference to OVA->OVF conversion

**Comment by VenkyOS** [comment]
@gregnsk and @mukul-seagate11 - The below mentioned PR should sort this issue.

https://github.com/Seagate/cortx/pull/705
