### ISSUE TITLE
Clean up https://github.com/Seagate/cortx/blob/main/doc/GitHub_Processes_and_Tools.rst

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#706]
Hey @Saumya-Sunder ,

Can you add a Table of Contents with Quick Links at the top of this page please?  Or can you do your nice 'Click To Expand' on all of the sections?  Right now, it is too hard to navigate and find what useful info is on this page?

Also, can you please add a section about 'WYSIWYG in GitHub' please?  And include the info in the email I just sent about the browser extensions (subject: Useful browser extensions)?

Thanks!

John

**Comment by Saumya-Sunder** [comment]
Hey @johnbent , done here https://github.com/Seagate/cortx/pull/781/files
