### ISSUE TITLE
Ready make docker image

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx#711]
Hi, 

I was reading [Release Build Creation](../blob/main/doc/Release_Build_Creation.rst), and seem like need to make docker image our self.

Just wondering do we got any ready make docker image can just load and run immediately ? 

I was plan to run the docker image on Windows 10.

Regards,
kiwi

**Comment by mukul-seagate11** [comment]
Thanks for opening this issue. A contributor should be by to give feedback soon. In the meantime, please check out the [https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md](https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md) and explore other https://github.com/Seagate/cortx/

**Comment by mukul-seagate11** [comment]
@kiwionly2, You can incorporate OVA image as updated in [Release Virtual Appliance Releases · Seagate/cortx (github.com)](https://github.com/Seagate/cortx/releases/tag/VA) which is a Virtual Appliance based on CORTX software where you can import the same on VMware Workstation

Reference documentation: 

[cortx/CORTX\_on\_Open\_Virtual\_Appliance.rst at main · Seagate/cortx (github.com)](https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst)

[cortx/Preboarding\_and\_Onboarding.rst at main · Seagate/cortx (github.com)](https://github.com/Seagate/cortx/blob/main/doc/Preboarding_and_Onboarding.rst)

**Comment by kiwionly2** [comment]
I mean something like https://hub.docker.com/_/rabbitmq

Which I could just run 

```
$ docker run -d --hostname my-rabbit --name some-rabbit rabbitmq:3
```

**Comment by justinzw** [comment]
Hi @kiwionly2 thank you for your interest and question. Unfortunately at this time we do not have the ability to run CORTX within a docker container. 

As @mukul-seagate11 mentioned we do have the ability to run CORTX within a VM 
https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst

Would this work for you? I'm going to close this issue for now as it's something we are not supporting. But will certainly re-open if we have any updates on when we will provide docker support.

Also let me know if I misunderstood your question and you are referring to something else.
