### ISSUE TITLE
Unidentified team members

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#785]
Hello @PSO-Dmitry @Raja-Mohanty @rajeshdesh @sonalijadhav96 @sonalk0209 @vimleshsgt ,

The six of you are using github enterprises licenses for Seagate but we are unable to map your github IDs to your seagate email addresses.  Please either reply here with your email addresses or email them directly to me.  Thanks!

FYI @mukul-seagate11 and @Saumya-Sunder with whom I'm working to properly ensure license consumption.

**Comment by rajeshdesh** [comment]
Hi @johnbent , @mukul-seagate11 , @Saumya-Sunder ,

My email ID registered with @rajeshdesh is: rajesh.deshmukh@seagate.com

What do I need to make the corrections?

**Comment by johnbent** [comment]
You're good now.  Thanks!
________________________________

**Comment by sonalk0209** [comment]
Hi @John Bent<mailto:notifications@github.com> and @Mukul Malhotra<mailto:mukul.malhotra@seagate.com>

My mail id for my github id sonlak0209: sonal.kalbende@seagate.com
________________________________

**Comment by PSO-Dmitry** [comment]
Replied internally.
