### ISSUE TITLE
Please move wiki

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#797]
[https://github.com/Seagate/cortx/wiki/Build-Motr-from-Source-in-a-Cluster](https://github.com/Seagate/cortx/wiki/Build-Motr-from-Source-in-a-Cluster) I think this should be in the motr wiki not in the parent.  Patrick, can you move it please?  Also, you'll need to update all links to it.  There is one in the parent QSG.  Are there any others?

**Comment by hessio** [comment]
Think this is the only link, no worries, I will move it!

**Comment by johnbent** [comment]
Thanks Patrick!
