### ISSUE TITLE
Encryption Support w/ Post-Quantum

### ISSUE THREAD

**Issue by StephanSalas** [Seagate/cortx#800]
Are plans in the development roadmap to support post-quantum encryption for cortx? What plans do we currently have for distributed-storage encryption?

**Comment by justinzw** [comment]
@StephanSalas  thanks for asking this. We don't have plans to support post-quantum encryption. But I'd love to learn more about it. What type of distributed storage encryption would you like us to support and what use cases are you interested in using this for?
