### ISSUE TITLE
CentOS 8 Life cycle

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx#810]
It's been quite a while since the announcement of CentOS 8 EOL ([Table](https://wiki.centos.org/About/Product)) scheduled by December 2021.
Will Cortx stick to CentOS 7 (according to [LocalVMSetup](https://github.com/Seagate/cortx/blob/main/doc/LocalVMSetup.md)) for now while looking at other Linux distro or would go for CentOS Stream?

Consideration for [Rocky Linux](https://github.com/rocky-linux/rocky)?

**Comment by mukul-seagate11** [comment]
@shailesh-vaidya, can you address Harrison query as I see CentOS 8 in the roadmap but do we have any plan defined? I hope this might be a ARC call ?

**Comment by justinzw** [comment]
Thanks @harrison-seow-seagate I agree we should probably support the latest CentOS but what are the benefits of supporting Rocky Linux over CentOS.

Thanks for suggesting this!

**Comment by harrison-seow-seagate** [comment]
Hi @justinzw, the latest CentOS 8 will have no updates/maintenance by Dec 2021 (unless further migrate to CentOS Steam).
CentOS is famous for being a reliable Linux distribution (downstream of RHEL), but CentOS Stream is a development (upstream) branch of RHEL.

I would say it's generally a bad idea to use development branch for production use, also advised by Red Hat, to go for the paid RHEL if stability is needed.

Rocky Linux is intended to be 100% bug-to-bug compatible with Enterprise Linux, effectively replacing the gap left by CentOS 8 after its EOL. (_Though I can't say much about it in the current state as it's still new, but it's initiated by the founder of CentOS_)

I'm sure there are other people with better insights, but I would personally think CentOS Stream is probably not the best option.

**Comment by harrison-seow-seagate** [comment]
I'm not sure if this is categorized as an issue, perhaps this can be moved to discussion?

_However, I think it would be an issue if migration to CentOS 8 has started._

**Comment by mukul-seagate11** [comment]
> I'm not sure if this is categorized as an issue, perhaps this can be moved to discussion?
> 
> _However, I think it would be an issue if migration to CentOS 8 has started._

It will be a discussion as the migration to CentOS 8 yet not started
