### ISSUE TITLE
CORTX Quick Start Guide cluster link

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#820]
in https://github.com/Seagate/cortx/blob/main/QUICK_START.md

2. Build motr from the source: LINK
i.Run it on a single node: LINK
ii.Run it across a cluster: LINK

should we link i and ii to https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md?

**Comment by hessio** [comment]
Yes I can work on getting this done. In [https://github.com/Seagate/cortx/blob/main/QUICK_START.md](https://github.com/Seagate/cortx/blob/main/QUICK_START.md) we want to have at least a minimum of 2 people in the "tested by" section before we direct people to the link. But this is a great find! Thanks for this.

**Comment by hessio** [comment]
Hi @yanqingfu I am just after realizing that this is for internal only. You cannot access the repos outside of the Seagate network. Nonetheless we are super excited to see you contributing to the community and this was a great find nonetheless and a great question to ask.

**Comment by johnbent** [comment]
@hessio , we should made this guide work for external parties.  Why doesn't it?  

@yanqingfu , please keep helping us make our quick start guide better!  It is a major gap that there is no way to build and run the entire stack.  Have you ever been able to do that?

**Comment by yanqingfu** [comment]
@johnbent Hi John, I am able to run a single-node setup before as in the guide   https://github.com/Seagate/cortx/blob/main/doc/Cluster_Setup.md, but will try the setup for the latest release.

**Comment by hessio** [comment]
The repos that are being used are only available to people on the Seagate network. I am in the process of amending this to work for the open-source community.

**Comment by hessio** [comment]
Internal links removed. #857

**Comment by hessio** [comment]
Internal links removed. [#857](https://github.com/Seagate/cortx/pull/857)
