### ISSUE TITLE
Enable the EPEL repo, use:$ yum --enablerepo=extras install epel-release error 

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx#836]
[root@ssc-vm-1061 cortx]# yum --enablerepo=extras install epel-release
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.

Error getting repository data for extras, repository not found
Uploading Enabled Repositories Report

**Comment by mukul-seagate11** [comment]
@shailesh-vaidya, Can you look & verify the issue as reported?

**Comment by shailesh-vaidya** [comment]
@yanqingfu  - It seems you are using SSC VM as `ssc-vm-1061`. On these VM's EPEL repo is already enabled. You can proceed to the next step as `yum install python-pip` . Please try that out and let me know if you face any issues. 

@sachitanands We need to update the steps per environment.

**Comment by nileshgovande** [comment]
Merged https://github.com/Seagate/cortx-s3server/pull/773 to s3

**Comment by nileshgovande** [comment]
@mukul-seagate11 - Please close the issue.

**Comment by yanqingfu** [comment]
@shailesh-vaidya no issue to proceed
