### ISSUE TITLE
Community testimonials

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#838]
FYI @sainarasim and @novium258 , let's collect a bunch of quotes here and then make a page out of it.  So far, we have:

Intel: “Open-source innovation in high-performance storage is critical to propel cloud, HPC, AI and communications networks to higher levels of performance in the coming data era,” says Bryan Jorgensen, VP in Intel’s data platforms group. “Intel plans to work within the CORTX Community to enable and optimize this exciting open-source technology with our relevant platform features. We’ll also be working with Seagate to integrate those same technology innovations within the mass capacity-optimized Lyve Drive Rack reference design.”

Github: “Seagate delivers an open platform, with all the feature sets and roadmaps driven by the community—for the community,” says Jeff McAffer, senior director of product at GitHub. “It’s the kind of setting in which innovation happens.”

CEA: “CORTX is now proving to be a very powerful and flexible object storage, which can be used to implement very large-scale data storage,” says Jacques-Charles Lafoucriere, program manager, CEA.

Let's add ARM, UKAE, UW, UC, UMainz, Raytheon, and as many others as we can.

**Comment by johnbent** [comment]
@Saumya-Sunder , can you do the needful and convert this into a page in doc called 'community_testimonials.md' and then also add a link from our top-level README please?  Sort them alpha by company.  Make it a bullet list.  Make the company name be bold please.  Like:

- **CEA**
  - "quote" by person
- **LANL**
  - "quote by person

Etc.

Pull from the spreadsheet but only from green rows please because those are the only ones to which we have permission.  Thanks!

**Comment by Saumya-Sunder** [comment]
Sure John, I'm on it.

**Comment by sainarasim** [comment]
"CORTX is novel in its very concept. It is very exciting to try our application and explore its performance using this unique object data storage system" says Dr. Debasmita Samaddar, Exascale algorithms specialist, UK Atomic Energy Authority (UKAEA), a leader in fusion energy research and development.

**Comment by Saumya-Sunder** [comment]
Done [here](https://github.com/Seagate/cortx/pull/863) @johnbent please approve the changes. @mukul-seagate11 please close the issue once the PR is approved. I do not have access to close the issue.
