### ISSUE TITLE
Fatal error: Kernel devel source not available for required kernel version.

### ISSUE THREAD

**Issue by ttwalkertt** [Seagate/cortx#85]
https://github.com/Seagate/cortx/blob/master/doc/CortxMotrQuickStart.md has us run _sudo ./scripts/install-build-deps_ to install the build dependencies. The **script fails** when fetching the kernel source:

>TASK [base-os : install kernel-devel for the current kernel] ***************************************************************
>fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'kernel-devel-3.10.0-1062.el7.x86_64' found available, installed or updated", "rc": 126, "results": ["No package matching 'kernel-devel-3.10.0-1062.el7.x86_64' found available, installed or updated"]}
>...ignoring
>msg:  No package matching 'kernel-devel-3.10.0-1062.el7.x86_64' found available, installed or updated
>results:  No package matching 'kernel-devel-3.10.0-1062.el7.x86_64' found available, installed or updated

However, if the OS release is updated (sudo yum update) to pick up the current versions of Centos 7.7 packages, we get kernel 3.10.0-1127.13.1.el7.x86_64 which does have the devel package available.  After an update _./scripts/install-build-deps_ runs with no errors.

CortX team told me 3.10.0-1062 is required, however the build process won't complete unless the system is upgraded to 3.10.0-1127.  Please either **change the kernel requirement** away from 3.10.0-1062 or **make the 3.10.0-1062 dev source available** on Github.

In general we need to be able to update the Centos 7.7 distribution prior to use. It is important to keep these systems patched and updated for security and bug fixes. The update process brings an updated kernel. We should support current kernels, or understand the requirement that drives the need for an old kernel.

Thanks.

**Comment by johnbent** [comment]
@shailesh-vaidya is this fixed in the nice release dependencies page that you and @Saumya-Sunder worked on?

**Comment by shailesh-vaidya** [comment]
@johnbent  - We have not added kernel-devel packages in Build dependencies page. 

@ttwalkertt Sorry for quite delayed response on this one.  CentOS has moved to CentOS 7.8 and CORTX Team is also soon enable CentOS 7.8.2003 support with  3.10.0-1127 kernel. 
For current issue 3.10.0-1062.el7 kernel packages are removed from release mirrors however they are available at [vault ](https://vault.centos.org/7.7.1908/os/)repositories.  We can enable them by adding and enabling vault repo in you repo configuration

To test this,

On CentOS 7.7.1908 system execute below command,
```
 cat <<EOF >> /etc/yum.repos.d/CentOS-Vault.repo
> [C7.7.1908-base]
> name=CentOS-7.7.1908 - Base
> baseurl=http://vault.centos.org/7.7.1908/os/\$basearch/
> gpgcheck=1
> gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
> enabled=1
> EOF
```
Disable default Base and Updated repo as that will pull latest packages. 
```
yum-config-manager --disable base,updates
```
Now kernel-3.10.0-1062.el7 packages will be available as below,
```
[root@465269edbc62 /]# yum list kernel{,-devel}
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * extras: mirror.den01.meanservers.net
Available Packages
kernel.x86_64                                                                          3.10.0-1062.el7                                                                     C7.7.1908-base
kernel-devel.x86_64                                                                    3.10.0-1062.el7                                                                     C7.7.1908-base
[root@465269edbc62 /]#
```

**Comment by VenkyOS** [comment]
@johnbent - Shall I document the information provided by @shailesh-vaidya? Should it be documented in Motr Quick Start Guide?

**Comment by johnbent** [comment]
@VenkyOS , please test the motr quick start guide using your local VM and if these instructions make the quick start guide better, please add them accordingly.  Please do not just add them without testing though.

**Comment by VenkyOS** [comment]
@johnbent - Sure. I will test using the local VM.

**Comment by huanghua78** [comment]
I have tested and verified the "https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst" is fine.

Please refer to https://github.com/Seagate/cortx-motr/issues/217#issuecomment-736285749

**Comment by huanghua78** [comment]
I think this is fixed.
