### ISSUE TITLE
Upcoming Events page

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx#861]
@TechWriter-Mayur , can you please help with the following:

1.  Create a new wiki page called Upcoming\_Events.md
2.  Populate it with all the upcoming trainings and meet an architect meetings
    1.  I know this means we will have replicated work keeping these multiple pages up to date but we think it is worth the price
3.  Link to the new wiki page from the top-level README in an appropriate location

Thanks!

**Comment by TechWriter-Mayur** [comment]
The page has been created and available on the wiki.

**Comment by mukul-seagate11** [comment]
@johnbent , If all good then can we close the Issue reported

@TechWriter-Mayur, please update the PR created for community reference
