### ISSUE TITLE
Need document that explains how the different components in CORTX work

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx#869]
From feedback from @harrison-seow-seagate there needs to be a document that describes the different components in CORTX and how they all work together.

cc @johnbent

**Comment by hessio** [comment]
Hi @justinzw I can work on making one, however if you direct to any of these components' README there is a good explanation as to what the purpose of this component is.

**Comment by johnbent** [comment]
It would be nice to have a single page that consolidates from each of the README's (and links to each of them).  Like components.md in the parent

**Comment by johnbent** [comment]
Thanks @justinzw for creating this issue and thanks @hessio for doing the needful and thanks @harrison-seow-seagate for suggesting this!
