### ISSUE TITLE
just PUT & GET some kv pairs into a DIX

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx#887]
- The purpose of this task is to make a setup suitable for development
    environment.
  - The task

    - Make Hare CDF file for single node Motr/Hare setup
    - Bootstrap Motr/Hare cluster on a devvm
    - Make m0crate configuration ``.yaml`` file to PUT and GET a few kv pairs
      to/from an index
    - Run m0crate with this configuration file

  - Definition of done

    - Hare CDF file is attached to the issue
    - m0crate configuration file is attached to the issue
    - logs for bootstrap and for m0crate execution are posted as comments to
      this issue

  - References

    - https://github.com/Seagate/cortx-hare/blob/main/README.md

**Comment by max-seagate** [comment]
test highlight @somnathbghule

**Comment by somnathbghule** [comment]
I followed the Hare User Guide to create single node Motr/Hare cluster setup, here are the details,

pasting bootstrap logs:
[user@devvm ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-04-07 10:08:21: Generating cluster configuration... OK
2021-04-07 10:08:22: Starting Consul server on this node........... OK
2021-04-07 10:08:30: Importing configuration into the KV store... OK
2021-04-07 10:08:31: Starting Consul on other nodes... OK
2021-04-07 10:08:31: Updating Consul configuraton from the KV store... OK
2021-04-07 10:08:32: Waiting for the RC Leader to get elected....... OK
2021-04-07 10:08:36: Starting Motr (phase1, mkfs)... OK
2021-04-07 10:08:43: Starting Motr (phase1, m0d)... OK
2021-04-07 10:08:57: Starting Motr (phase2, mkfs)... OK
2021-04-07 10:09:05: Starting Motr (phase2, m0d)... OK
2021-04-07 10:09:19: Checking health of services... OK

[user@devvm ~]# hctl status
Data pool:
    # fid name
    0x6f00000000000001:0x1f 'the_pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x37 'default': 'the_pool' None None
Services:
    localhost  (RC)
    [started]  hax        0x7200000000000001:0x6   192.168.52.53@tcp:12345:1:1
    [started]  confd      0x7200000000000001:0x9   192.168.52.53@tcp:12345:2:1
    [started]  ioservice  0x7200000000000001:0xc   192.168.52.53@tcp:12345:2:2
    [unknown]  m0_client  0x7200000000000001:0x19  192.168.52.53@tcp:12345:4:1
    [unknown]  m0_client  0x7200000000000001:0x1c  192.168.52.53@tcp:12345:4:2
[root@ssc-vm-2410 ~]#

m0crate execution logs:
[user@devvm ~]# sudo m0crate -S /tmp/m0crate-index-1024-16384.yaml
info: starting workload 0
info: workload type          index/3
info: random seed:           0
info: number of threads:     1
info: dix: End of operations.
result: total_s, 0.015859, avg_time_per_op_ns, 7929371.0, key_size_bytes, 1024, value_size_bytes, 16384, ops, 2
result: PUT, total_time_s, 0.009765, avg_time_per_op_ns, 9765121.0, ops, 1
result: GET, total_time_s, 0.002798, avg_time_per_op_ns, 2798042.0, ops, 1
result: NEXT, total_time_s, 0.000000, avg_time_per_op_ns, 0.0, ops, 0
result: DEL, total_time_s, 0.000000, avg_time_per_op_ns, 0.0, ops, 0

Total: time=[0:015858742] ([0:007929371] per op) ops=2
PUT: [0:009765121] ([0:009765121] per op) ops=1
GET: [0:002798042] ([0:002798042] per op) ops=1
info: done workload 0
info: ---------------------------------------

**Comment by mukul-seagate11** [comment]
@max-seagate, I hope, component related issue should be created in respective component issues page

**Comment by johnbent** [comment]
@kaustubh-d , should @max-seagate be using the Project board instead of Issues?

**Comment by kaustubh-d** [comment]
> @kaustubh-d , should @max-seagate be using the Project board instead of Issues?

@johnbent  This issue is added to multisite project board but updates have to be on issue.
