### ISSUE TITLE
Add a new Motr client application which is going to be used as a scheduler for multisite work

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx#888]
- The purpose of the task is to make FDMI plugin application that is able to
    connect to a Motr/Hare cluster
  - The task

    - create a branch ``fdmi-plugin-multisite`` in Motr repo based on ``main``
    - add a new binary ``m0sched`` to ``fdmi/plugins`` directory
    - the binary MUST:

      - be built by default with Motr build
      - be included in Motr rpm
      - take 4 parameters: process endpoint, process fid, HA endpoint, profile
        fid
      - initialise Motr client
      - wait for ``SIGINT`` or ``SIGTERM`` after the client is initialised
      - finialise Motr client when either ``SIGINT`` or ``SIGTERM`` are
        received

    - ``m0_semaphore`` MUST be used to wake up main thread when the signal
      arrives
    - add instructions to start this new binary to ``doc/m0sched.rst``

  - Definition of done

    - ``m0sched`` source code is in ``fdmi-plugin-multisite`` branch in Motr
      repo
    - instructions to build and run the binary are reproducible on devvm
    - ``m0sched`` is a part of Motr rpm
    - ``m0sched`` is running until ^C (``SIGINT``) or ``SIGTERM`` arrive

  - References

    - https://github.com/Seagate/cortx-motr/blob/main/doc/source-structure.md#how-to-add-a-new-executable
    - see how ``m0ham`` is added to the build system (``git grep -n m0ham``)

**Comment by kaustubh-d** [comment]
Please describe each task more clearly

**Comment by somnathbghule** [comment]
Task completion list:
1. Added new motr client application m0sched and pushed changes to fdmi-plugin-multisite.
https://github.com/somnathbghule/cortx-motr/tree/fdmi-plugin-multisite
2. m0sched will be build along with motr.
3. added source changes so that m0sched will be part of motr rpm.
4. m0sched developed in such way that m0sched is running until ^C (SIGINT) or SIGTERM arrive.

m0sched execution:
```
[root@devvm ~]# m0sched -l 192.168.52.53@tcp:12345:4:1 -h 192.168.52.53@tcp:12345:1:1 -p 0x7000000000000001:0x37 -f 0x7200000000000001:0x19
Plugin registration rc: 0
m0sched waiting for signal...


[root@devvm ~]# m0sched -i
Usage: m0sched -l local_addr -h ha_addr -p profile_fid -f process_fid
Use -? or -i for more verbose help on common arguments.
Usage example for common arguments:
m0sched -l 192.168.52.53@tcp:12345:4:1 -h 192.168.52.53@tcp:12345:1:1 -p 0x7000000000000001:0x37 -f 0x7200000000000001:0x19
[root@devvm ~]# m0sched -?
Usage: m0sched options...

where valid options are

         -?           : display this help and exit
         -i           : more verbose help
         -l     string: Local endpoint address
         -h     string: HA address
         -f     string: Process FID
         -p     string: Profile options for Client
```
