### ISSUE TITLE
make design for scheduler written in Python + C and worker written in Python

### ISSUE THREAD

**Issue by max-seagate** [Seagate/cortx#901]
- The purpose of this task is to evaluate feasibility of Python as a language
    for scheduler logic and worker logic
  - The task

    - design scheduler logic
    - design C and Python interfaces between C part of the scheduler and Python
      part of the scheduler
    - design worker logic
    - design communication interface between scheduler and worker
    - design persistent state machines for scheduler
    - design FDMI record persistence & deduplication on scheduler
    - get all designs reviewed

  - Definition of done

    - designs from the list above are available for review
    - designs from the list above are reviewed

**Comment by max-seagate** [comment]
Work in progress: https://github.com/Seagate/cortx-multisite/blob/main/doc/replication.rst and https://github.com/Seagate/cortx-multisite/blob/main/doc/replication-dld.rst.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~532357] [~744292] [~720600]

This appears to be looking at some decisions about replication design.  Is this inherently resolved with RGW?  I assume this functionality already exists there?  or we still have to add this worker/scheduler capability?

**Comment by cortx-admin** [comment]
> Ujjwal Lanjewar commented in Jira Server:

In the current form, this ticket is invalid as it depends on legacy S3 design. This may need to redesigned with RGW differently.

**Comment by cortx-admin** [comment]
> Ujjwal Lanjewar commented in Jira Server:

{quote}why would we need to evaluate the best language if it already exists in RGW? 
{quote}
Yes, this is the reason, I mentioned that this ticket is invalid and needs to be relooked/redesign. RGW does not have python and like this may already be there in C++. RGW has threads unlike legacy S3 server with multiple processes.

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~720600] [~533453]

Does this already exist in RGW (this scheduler function this appears to be referring to)?  If so, we should close this as no work or something as it already exists in RGW

**Comment by cortx-admin** [comment]
> Chetan Deshmukh commented in Jira Server:

we should close it, for reasons given by Ujjwal already, doesnt apply in RGW

**Comment by cortx-admin** [comment]
> Donald R Bloyer commented in Jira Server:

[~533453]  I think what you are saying is that the language decision is already de facto as we are using RGW (ie C++)

[~535110] this ticket is unassigned from Board Genius.  I do not know what protocol we used to assign this for someone to close?  Would this be closed by Ruth or someone?  I assigned to you in the interim.

**Comment by cortx-admin** [comment]
> Chetan Deshmukh commented in Jira Server:

{quote} I think what you are saying is that the language decision is already de facto as we are using RGW (ie C++)
{quote}
yes [~211146]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
