### ISSUE TITLE
Images on main CORTX page are gone!

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx#904]
In README.md we are missing images that used to be there:

![image](https://user-images.githubusercontent.com/950172/114211155-25a70d80-9915-11eb-896b-1b37616a857b.png)

https://github.com/Seagate/cortx/blob/assets/images/at_risk_data.jpg?raw=true

and

https://github.com/Seagate/cortx/blob/assets/images/cortx-logo.png?raw=true

are no longer there.

**Comment by johnbent** [comment]
Saumya, can you please find and restore these images?  @Saumya-Sunder

**Comment by Saumya-Sunder** [comment]
Sure @johnbent I am on it.

**Comment by Saumya-Sunder** [comment]
Looks like these images were optimized by bot https://github.com/Seagate/cortx/pull/881 I am trying to see if the format has changed or they are still there. I will update the PR with changes here once done @johnbent and @justinzw
