### ISSUE TITLE
Add support for el8

### ISSUE THREAD

**Issue by Jeetandra** [Seagate/cortx#93]
Current mero repository works with Centos7.7.

Plan is to add support for Centos8 (starting with CentOS8.2)

@huanghua78 @justinzw @johnbent

**Comment by Jeetandra** [comment]
hey everyone, I have re-forked from crotx-motr project and have included the changes. They are now available at https://github.com/Jeetandra/cortx-motr/
I'll start working on adding support for el8 for cortx-s3server

**Comment by mukul-seagate11** [comment]
@Jeetandra, thank you for testing so closing this issue  and feel free to open another issue if you encounter any other issue
