### ISSUE TITLE
cortx-experiments presence fails stable builds

### ISSUE THREAD

**Issue by ypise** [Seagate/cortx#936]
**cortx-experiments** doesn't have a stable branch https://github.com/Seagate/cortx-experiments/branches/all?query=stable
This causes step #4 of [Release Build Creation](https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst#procedure) to fail.

This raises the real concern of, is **_cortx-experiments_** still required to be part of https://github.com/Seagate/cortx?

**Comment by mukul-seagate11** [comment]
@ypise, stable branch has been created now, https://github.com/Seagate/cortx-experiments/tree/stable
