### ISSUE TITLE
Release Build Creation doc expects root access

### ISSUE THREAD

**Issue by ypise** [Seagate/cortx#939]
https://github.com/Seagate/cortx/blob/main/doc/Release_Build_Creation.rst expects the commands to be run as root.
Any user with sudoer access should be able to execute these commands.

**Comment by mukul-seagate11** [comment]
@gowthamchinna, please address the issue reported?

**Comment by shailesh-vaidya** [comment]
@mukul-seagate11 Steps will work by appending `sudo` for commands and use directory with user having access. I see that @ypise already working on https://github.com/Seagate/cortx/pull/942 for it. 

@ypise Just for note, We expect user to Build and then perform deployment also. For Deployment we need `root` user access as of now.

**Comment by mukul-seagate11** [comment]
Can this issue be update?

**Comment by ypise** [comment]
The documents have been updated and this issues is no longer relevant.
