### ISSUE TITLE
Release Build in containerized environment fails on EC2 instance with CentOS 7.9 OS

### ISSUE THREAD

**Issue by ypise** [Seagate/cortx#941]
Release Build in containerized environment fails on EC2 instance with CentOS 7.9 OS

> Error: No Package found for kernel-devel = 3.10.0-1062.12.1.el7
> ERROR: cortx-motr source code is not available in cortx-workspace. Exiting...

This kernel-devel package is found under: https://vault.centos.org/7.7.1908/os/x86_64/Packages/

Package this rpm in image: ghcr.io/seagate/cortx-build:centos-7.8.2003

**NOTE**: Containerized builds should work irrespective of the version of host OS.

**Comment by mukul-seagate11** [comment]
@ypise, similar issue with resolution is reported in https://github.com/Seagate/cortx/issues/864
please refer & validate the same steps as suggested

**Comment by shailesh-vaidya** [comment]
@ypise  I validated CORTX build for both centos 7.9.2009 and centos 7.8.2003 and does not face any issues. 

We need to use Docker image and Virtual Machine with same OS version. Means to generate CentOS 7.9.2009, We should setup CentOS 7.9.2009 VM and use Docker Image with tag [centos-7.9.2009](https://github.com/orgs/Seagate/packages/container/cortx-build/1259276?tag=centos-7.9.2009). I guess this is requirement from Motr Build steps. @madhavemuri may be you can clarify more.

**Comment by ypise** [comment]
Sounds good.
