### ISSUE TITLE
Virtual Box VMs may not have network devices setup right

### ISSUE THREAD

**Issue by adgang** [Seagate/cortx#985]
The `For Oracle VM VirtualBox Users Only' section in [VM setup documentation](https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst#cortx-on-open-virtual-appliance) is sometimes not reproducible.

1. Network devices can have different names(enp0s8, enp0s9, enp0s17 instead of  enp0s3, enp0s8, enp0s9)See [here](https://youtu.be/-JPrpL1_8Mg?t=801)
2. Restarting VM sometimes switches the IPs of network devices. See initially [here](https://youtu.be/-JPrpL1_8Mg?t=801) and after restart [here](https://youtu.be/-JPrpL1_8Mg?t=2153)

Tested on:
MacOS: 10.15.5
Oracle VirtualBox: Version 6.0.4 r128413 (Qt5.6.3)
Cortx image: cortx-va-1.0.3.va

**Comment by harrison-seow-seagate** [comment]
Hi @adgang, the Oracle VM VirtualBox instructions was initially documented using cortx ova 1.0.2, which for some reason has different device names compared to cortx ova 1.0.3. (So this part may need to improve, if anyone knows the reason behind).

Restarting the VM switches the IP address seems reasonable to me, maybe you want to further elaborate what kind of trouble are you having?

**Comment by adgang** [comment]
Actually, I was able to see enp0s3, enp0s8, enp0s9 device names when I ran Cortx in an earlier VM using Cortx ova 1.0.3. 

What I mean by the `Restarting VM sometimes switches the IPs` issue is that if I had been using one IP, ip1, for management portal and another, ip2, for public services(like s3), after restarting VM, the management portal no longer is available on ip1 but is on ip2.

**Comment by mukul-seagate11** [comment]
@adgang, the instructions are already documented in https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst in steps 6. "For Oracle VM VirtualBox Users ONLY"

**Comment by harrison-seow-seagate** [comment]
As the network is setup using DHCP, IP changes are bound to happen during restart, static IP configuration could be harder to maintain as it may not work for different VM with different network setups.
